// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_claims.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const cleanupDeliveredClaims = `-- name: CleanupDeliveredClaims :exec
DELETE FROM agent_claims 
WHERE claimed_at IS NOT NULL 
  AND api_key_delivered = 1
  AND claimed_at < datetime('now', '-1 hour')
`

func (q *Queries) CleanupDeliveredClaims(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupDeliveredClaims)
	return err
}

const cleanupExpiredClaims = `-- name: CleanupExpiredClaims :exec
DELETE FROM agent_claims 
WHERE claim_token_expires_at < datetime('now')
`

func (q *Queries) CleanupExpiredClaims(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredClaims)
	return err
}

const createAgentClaim = `-- name: CreateAgentClaim :one
INSERT INTO agent_claims (
    id,
    claim_token_hash,
    hostname,
    agent_version,
    claim_token_expires_at
) VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateAgentClaimParams struct {
	ID                  string
	ClaimTokenHash      string
	Hostname            string
	AgentVersion        string
	ClaimTokenExpiresAt time.Time
}

func (q *Queries) CreateAgentClaim(ctx context.Context, arg CreateAgentClaimParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAgentClaim,
		arg.ID,
		arg.ClaimTokenHash,
		arg.Hostname,
		arg.AgentVersion,
		arg.ClaimTokenExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAgentClaim = `-- name: GetAgentClaim :one
SELECT id, claim_token_hash, hostname, agent_version, claim_token_expires_at, last_seen_at, created_at, claimed_at, claimed_by_user_id, api_key_plaintext, api_key_delivered FROM agent_claims
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAgentClaim(ctx context.Context, id string) (AgentClaim, error) {
	row := q.db.QueryRowContext(ctx, getAgentClaim, id)
	var i AgentClaim
	err := row.Scan(
		&i.ID,
		&i.ClaimTokenHash,
		&i.Hostname,
		&i.AgentVersion,
		&i.ClaimTokenExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedByUserID,
		&i.ApiKeyPlaintext,
		&i.ApiKeyDelivered,
	)
	return i, err
}

const getAgentClaimForClaiming = `-- name: GetAgentClaimForClaiming :one
SELECT id, claim_token_hash, hostname, agent_version, claim_token_expires_at, last_seen_at, created_at, claimed_at, claimed_by_user_id, api_key_plaintext, api_key_delivered FROM agent_claims
WHERE id = ?
  AND claim_token_hash = ?
  AND claim_token_expires_at > datetime('now')
  AND claimed_at IS NULL
LIMIT 1
`

type GetAgentClaimForClaimingParams struct {
	ID             string
	ClaimTokenHash string
}

// Used when user attempts to claim an agent
func (q *Queries) GetAgentClaimForClaiming(ctx context.Context, arg GetAgentClaimForClaimingParams) (AgentClaim, error) {
	row := q.db.QueryRowContext(ctx, getAgentClaimForClaiming, arg.ID, arg.ClaimTokenHash)
	var i AgentClaim
	err := row.Scan(
		&i.ID,
		&i.ClaimTokenHash,
		&i.Hostname,
		&i.AgentVersion,
		&i.ClaimTokenExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimedByUserID,
		&i.ApiKeyPlaintext,
		&i.ApiKeyDelivered,
	)
	return i, err
}

const getPendingAPIKeyDelivery = `-- name: GetPendingAPIKeyDelivery :one
SELECT 
    ac.id,
    ac.claimed_at,
    ac.api_key_plaintext
FROM agent_claims ac
WHERE ac.id = ?
  AND ac.claimed_at IS NOT NULL
  AND ac.api_key_delivered = 0
  AND ac.api_key_plaintext IS NOT NULL
LIMIT 1
`

type GetPendingAPIKeyDeliveryRow struct {
	ID              string
	ClaimedAt       sql.NullString
	ApiKeyPlaintext sql.NullString
}

// Agent polls this to get API key after being claimed
func (q *Queries) GetPendingAPIKeyDelivery(ctx context.Context, id string) (GetPendingAPIKeyDeliveryRow, error) {
	row := q.db.QueryRowContext(ctx, getPendingAPIKeyDelivery, id)
	var i GetPendingAPIKeyDeliveryRow
	err := row.Scan(&i.ID, &i.ClaimedAt, &i.ApiKeyPlaintext)
	return i, err
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT id, claim_token_hash, hostname, agent_version, claim_token_expires_at, last_seen_at, created_at, claimed_at, claimed_by_user_id, api_key_plaintext, api_key_delivered FROM agent_claims
WHERE claimed_at IS NOT NULL
  AND api_key_delivered = 0
ORDER BY claimed_at ASC
`

func (q *Queries) ListPendingDeliveries(ctx context.Context) ([]AgentClaim, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentClaim
	for rows.Next() {
		var i AgentClaim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimTokenHash,
			&i.Hostname,
			&i.AgentVersion,
			&i.ClaimTokenExpiresAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimedByUserID,
			&i.ApiKeyPlaintext,
			&i.ApiKeyDelivered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclaimedAgents = `-- name: ListUnclaimedAgents :many

SELECT id, claim_token_hash, hostname, agent_version, claim_token_expires_at, last_seen_at, created_at, claimed_at, claimed_by_user_id, api_key_plaintext, api_key_delivered FROM agent_claims
WHERE claimed_at IS NULL
  AND claim_token_expires_at > datetime('now')
ORDER BY created_at DESC
`

// Keep for 1 hour after delivery
func (q *Queries) ListUnclaimedAgents(ctx context.Context) ([]AgentClaim, error) {
	rows, err := q.db.QueryContext(ctx, listUnclaimedAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentClaim
	for rows.Next() {
		var i AgentClaim
		if err := rows.Scan(
			&i.ID,
			&i.ClaimTokenHash,
			&i.Hostname,
			&i.AgentVersion,
			&i.ClaimTokenExpiresAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.ClaimedByUserID,
			&i.ApiKeyPlaintext,
			&i.ApiKeyDelivered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentClaimAPIKeyDelivered = `-- name: MarkAgentClaimAPIKeyDelivered :exec
UPDATE agent_claims
SET api_key_delivered = 1,
    api_key_plaintext = NULL  -- Clear plaintext key after delivery
WHERE id = ?
`

func (q *Queries) MarkAgentClaimAPIKeyDelivered(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markAgentClaimAPIKeyDelivered, id)
	return err
}

const markAgentClaimClaimed = `-- name: MarkAgentClaimClaimed :exec
UPDATE agent_claims
SET claimed_at = datetime('now'),
    claimed_by_user_id = ?,
    api_key_plaintext = ?
WHERE id = ?
`

type MarkAgentClaimClaimedParams struct {
	ClaimedByUserID sql.NullString
	ApiKeyPlaintext sql.NullString
	ID              string
}

func (q *Queries) MarkAgentClaimClaimed(ctx context.Context, arg MarkAgentClaimClaimedParams) error {
	_, err := q.db.ExecContext(ctx, markAgentClaimClaimed, arg.ClaimedByUserID, arg.ApiKeyPlaintext, arg.ID)
	return err
}

const upsertAgentClaim = `-- name: UpsertAgentClaim :one
INSERT INTO agent_claims (
    id,
    claim_token_hash,
    hostname,
    agent_version,
    claim_token_expires_at,
    last_seen_at
) VALUES (?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(id) DO UPDATE SET
    last_seen_at = datetime('now'),
    hostname = COALESCE(excluded.hostname, hostname),
    agent_version = COALESCE(excluded.agent_version, agent_version)
WHERE claimed_at IS NULL  -- Only update if not yet claimed
RETURNING id
`

type UpsertAgentClaimParams struct {
	ID                  string
	ClaimTokenHash      string
	Hostname            string
	AgentVersion        string
	ClaimTokenExpiresAt time.Time
}

func (q *Queries) UpsertAgentClaim(ctx context.Context, arg UpsertAgentClaimParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertAgentClaim,
		arg.ID,
		arg.ClaimTokenHash,
		arg.Hostname,
		arg.AgentVersion,
		arg.ClaimTokenExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
