// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package queries

import (
	"context"
	"database/sql"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, section_id, name, api_key_hash, base_config) VALUES 
(?, ?, ?, ?, ?)
RETURNING id
`

type CreateAgentParams struct {
	ID         string
	SectionID  string
	Name       string
	ApiKeyHash string
	BaseConfig string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.SectionID,
		arg.Name,
		arg.ApiKeyHash,
		arg.BaseConfig,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAgentConfigurationBase = `-- name: GetAgentConfigurationBase :one
SELECT id, version, name, base_config FROM agents WHERE id = ?
LIMIT 1
`

type GetAgentConfigurationBaseRow struct {
	ID         string
	Version    int64
	Name       string
	BaseConfig string
}

func (q *Queries) GetAgentConfigurationBase(ctx context.Context, id string) (GetAgentConfigurationBaseRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentConfigurationBase, id)
	var i GetAgentConfigurationBaseRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.BaseConfig,
	)
	return i, err
}

const getAgentEndpoints = `-- name: GetAgentEndpoints :many
SELECT id, address, port, enabled FROM endpoints WHERE agent_id = ?
`

type GetAgentEndpointsRow struct {
	ID      string
	Address string
	Port    sql.NullInt64
	Enabled int64
}

func (q *Queries) GetAgentEndpoints(ctx context.Context, agentID string) ([]GetAgentEndpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentEndpoints, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentEndpointsRow
	for rows.Next() {
		var i GetAgentEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Port,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentTags = `-- name: GetAgentTags :many
SELECT t.name FROM agent_tags at
JOIN tags t ON at.tag_id = t.id
WHERE at.agent_id = ? AND t.scope IN ('agent', 'global')
`

func (q *Queries) GetAgentTags(ctx context.Context, agentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAgentTags, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEndpointTags = `-- name: GetEndpointTags :many
SELECT t.name FROM endpoint_tags et
JOIN tags t ON et.tag_id = t.id
WHERE et.endpoint_id = ? AND t.scope IN ('endpoint', 'global')
`

func (q *Queries) GetEndpointTags(ctx context.Context, endpointID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEndpointTags, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentConfiguration = `-- name: UpdateAgentConfiguration :exec
UPDATE agents
SET version = ?, base_config = ?
WHERE id = ?
`

type UpdateAgentConfigurationParams struct {
	Version    int64
	BaseConfig string
	ID         string
}

func (q *Queries) UpdateAgentConfiguration(ctx context.Context, arg UpdateAgentConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentConfiguration, arg.Version, arg.BaseConfig, arg.ID)
	return err
}

const verifyAgentAPIKey = `-- name: VerifyAgentAPIKey :one
SELECT id, api_key_hash FROM agents WHERE id = ?
`

type VerifyAgentAPIKeyRow struct {
	ID         string
	ApiKeyHash string
}

func (q *Queries) VerifyAgentAPIKey(ctx context.Context, id string) (VerifyAgentAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, verifyAgentAPIKey, id)
	var i VerifyAgentAPIKeyRow
	err := row.Scan(&i.ID, &i.ApiKeyHash)
	return i, err
}
