// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const countAgentsByTenant = `-- name: CountAgentsByTenant :one
SELECT COUNT(*) FROM agents a
JOIN sections s ON a.section_id = s.id
WHERE s.tenant_id = ?
`

// Returns total count of agents belonging to all sections of a given tenant.
func (q *Queries) CountAgentsByTenant(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, section_id, name, api_key_hash, base_config) VALUES 
(?, ?, ?, ?, ?)
RETURNING id
`

type CreateAgentParams struct {
	ID         string
	SectionID  string
	Name       string
	ApiKeyHash string
	BaseConfig string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.SectionID,
		arg.Name,
		arg.ApiKeyHash,
		arg.BaseConfig,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createAgentFromClaim = `-- name: CreateAgentFromClaim :one
INSERT INTO agents (
    id,
    section_id,
    name,
    api_key_hash,
    base_config,
    agent_version,
    ip_addresses_json
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateAgentFromClaimParams struct {
	ID              string
	SectionID       string
	Name            string
	ApiKeyHash      string
	BaseConfig      string
	AgentVersion    sql.NullString
	IpAddressesJson string
}

// Creates an agent after successful claim
// name param should be initialized from agent_claims.hostname
func (q *Queries) CreateAgentFromClaim(ctx context.Context, arg CreateAgentFromClaimParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createAgentFromClaim,
		arg.ID,
		arg.SectionID,
		arg.Name,
		arg.ApiKeyHash,
		arg.BaseConfig,
		arg.AgentVersion,
		arg.IpAddressesJson,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAgentConfigurationBase = `-- name: GetAgentConfigurationBase :one
SELECT id, config_version, name, base_config FROM agents WHERE id = ?
LIMIT 1
`

type GetAgentConfigurationBaseRow struct {
	ID            string
	ConfigVersion int64
	Name          string
	BaseConfig    string
}

func (q *Queries) GetAgentConfigurationBase(ctx context.Context, id string) (GetAgentConfigurationBaseRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentConfigurationBase, id)
	var i GetAgentConfigurationBaseRow
	err := row.Scan(
		&i.ID,
		&i.ConfigVersion,
		&i.Name,
		&i.BaseConfig,
	)
	return i, err
}

const getAgentTags = `-- name: GetAgentTags :many
SELECT t.name FROM agent_tags at
JOIN tags t ON at.tag_id = t.id
WHERE at.agent_id = ? AND t.scope IN ('agent', 'global')
`

func (q *Queries) GetAgentTags(ctx context.Context, agentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAgentTags, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEndpointTags = `-- name: GetEndpointTags :many
SELECT t.name FROM endpoint_tags et
JOIN tags t ON et.tag_id = t.id
WHERE et.endpoint_id = ? AND t.scope IN ('endpoint', 'global')
`

func (q *Queries) GetEndpointTags(ctx context.Context, endpointID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEndpointTags, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByTenant = `-- name: ListAgentsByTenant :many
SELECT a.id, a.section_id, a.name, a.config_version, a.agent_version,
       a.ip_addresses_json, a.last_seen_at, a.last_result_submitted_at,
       a.updated_at, a.created_at
FROM agents a
JOIN sections s ON a.section_id = s.id
WHERE s.tenant_id = ?
ORDER BY a.created_at DESC
LIMIT ? OFFSET ?
`

type ListAgentsByTenantParams struct {
	TenantID string
	Limit    int64
	Offset   int64
}

type ListAgentsByTenantRow struct {
	ID                    string
	SectionID             string
	Name                  string
	ConfigVersion         int64
	AgentVersion          sql.NullString
	IpAddressesJson       string
	LastSeenAt            sql.NullTime
	LastResultSubmittedAt sql.NullTime
	UpdatedAt             time.Time
	CreatedAt             time.Time
}

// Returns paginated agents belonging to all sections of a given tenant.
func (q *Queries) ListAgentsByTenant(ctx context.Context, arg ListAgentsByTenantParams) ([]ListAgentsByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsByTenantRow
	for rows.Next() {
		var i ListAgentsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Name,
			&i.ConfigVersion,
			&i.AgentVersion,
			&i.IpAddressesJson,
			&i.LastSeenAt,
			&i.LastResultSubmittedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentConfiguration = `-- name: UpdateAgentConfiguration :exec
UPDATE agents
SET config_version = ?, base_config = ?
WHERE id = ?
`

type UpdateAgentConfigurationParams struct {
	ConfigVersion int64
	BaseConfig    string
	ID            string
}

func (q *Queries) UpdateAgentConfiguration(ctx context.Context, arg UpdateAgentConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentConfiguration, arg.ConfigVersion, arg.BaseConfig, arg.ID)
	return err
}

const updateAgentLastResultSubmittedAt = `-- name: UpdateAgentLastResultSubmittedAt :exec
UPDATE agents SET last_result_submitted_at = ? WHERE id = ?
`

type UpdateAgentLastResultSubmittedAtParams struct {
	LastResultSubmittedAt sql.NullTime
	ID                    string
}

func (q *Queries) UpdateAgentLastResultSubmittedAt(ctx context.Context, arg UpdateAgentLastResultSubmittedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentLastResultSubmittedAt, arg.LastResultSubmittedAt, arg.ID)
	return err
}

const updateAgentLastSeen = `-- name: UpdateAgentLastSeen :exec
UPDATE agents SET last_seen_at = ? WHERE id = ?
`

type UpdateAgentLastSeenParams struct {
	LastSeenAt sql.NullTime
	ID         string
}

func (q *Queries) UpdateAgentLastSeen(ctx context.Context, arg UpdateAgentLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentLastSeen, arg.LastSeenAt, arg.ID)
	return err
}

const verifyAgentAPIKey = `-- name: VerifyAgentAPIKey :one
SELECT id, api_key_hash FROM agents WHERE id = ?
`

type VerifyAgentAPIKeyRow struct {
	ID         string
	ApiKeyHash string
}

func (q *Queries) VerifyAgentAPIKey(ctx context.Context, id string) (VerifyAgentAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, verifyAgentAPIKey, id)
	var i VerifyAgentAPIKeyRow
	err := row.Scan(&i.ID, &i.ApiKeyHash)
	return i, err
}
