// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_vitals.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const getAgentVitalsHistory = `-- name: GetAgentVitalsHistory :many
SELECT id, agent_id, cpu_pct, mem_used_mb, mem_total_mb, system_uptime_secs, reported_at, received_at
FROM agent_vitals
WHERE agent_id = ?
  AND reported_at >= ?
  AND reported_at <= ?
ORDER BY reported_at ASC
`

type GetAgentVitalsHistoryParams struct {
	AgentID      string
	ReportedAt   time.Time
	ReportedAt_2 time.Time
}

func (q *Queries) GetAgentVitalsHistory(ctx context.Context, arg GetAgentVitalsHistoryParams) ([]AgentVital, error) {
	rows, err := q.db.QueryContext(ctx, getAgentVitalsHistory, arg.AgentID, arg.ReportedAt, arg.ReportedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentVital
	for rows.Next() {
		var i AgentVital
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CpuPct,
			&i.MemUsedMb,
			&i.MemTotalMb,
			&i.SystemUptimeSecs,
			&i.ReportedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAgentVitals = `-- name: GetLatestAgentVitals :one
SELECT id, agent_id, cpu_pct, mem_used_mb, mem_total_mb, system_uptime_secs, reported_at, received_at
FROM agent_vitals
WHERE agent_id = ?
ORDER BY reported_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentVitals(ctx context.Context, agentID string) (AgentVital, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentVitals, agentID)
	var i AgentVital
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CpuPct,
		&i.MemUsedMb,
		&i.MemTotalMb,
		&i.SystemUptimeSecs,
		&i.ReportedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const insertAgentVitals = `-- name: InsertAgentVitals :exec
INSERT INTO agent_vitals (
    id,
    agent_id,
    cpu_pct,
    mem_used_mb,
    mem_total_mb,
    system_uptime_secs,
    reported_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAgentVitalsParams struct {
	ID               string
	AgentID          string
	CpuPct           sql.NullFloat64
	MemUsedMb        sql.NullFloat64
	MemTotalMb       sql.NullFloat64
	SystemUptimeSecs sql.NullInt64
	ReportedAt       time.Time
}

func (q *Queries) InsertAgentVitals(ctx context.Context, arg InsertAgentVitalsParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentVitals,
		arg.ID,
		arg.AgentID,
		arg.CpuPct,
		arg.MemUsedMb,
		arg.MemTotalMb,
		arg.SystemUptimeSecs,
		arg.ReportedAt,
	)
	return err
}
