// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checks.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const checkResultExists = `-- name: CheckResultExists :one
SELECT id FROM check_results WHERE id = ? LIMIT 1
`

func (q *Queries) CheckResultExists(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, checkResultExists, id)
	err := row.Scan(&id)
	return id, err
}

const insertCheckResult = `-- name: InsertCheckResult :exec
INSERT INTO check_results (
    id,
    agent_id,
    endpoint_id,
    check_type,
    success,
    checked_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCheckResultParams struct {
	ID         string
	AgentID    string
	EndpointID string
	CheckType  string
	Success    int64
	CheckedAt  time.Time
}

func (q *Queries) InsertCheckResult(ctx context.Context, arg InsertCheckResultParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckResult,
		arg.ID,
		arg.AgentID,
		arg.EndpointID,
		arg.CheckType,
		arg.Success,
		arg.CheckedAt,
	)
	return err
}

const insertHttpGetCheckResult = `-- name: InsertHttpGetCheckResult :exec
INSERT INTO check_results_http_get (
    check_id,
    status_code,
    response_time_ms,
    response_size_bytes,
    error
) VALUES (?, ?, ?, ?, ?)
`

type InsertHttpGetCheckResultParams struct {
	CheckID           string
	StatusCode        int64
	ResponseTimeMs    sql.NullFloat64
	ResponseSizeBytes sql.NullInt64
	Error             sql.NullString
}

func (q *Queries) InsertHttpGetCheckResult(ctx context.Context, arg InsertHttpGetCheckResultParams) error {
	_, err := q.db.ExecContext(ctx, insertHttpGetCheckResult,
		arg.CheckID,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.ResponseSizeBytes,
		arg.Error,
	)
	return err
}

const insertPingCheckResult = `-- name: InsertPingCheckResult :exec
INSERT INTO check_results_ping (
    check_id,
    resolved_ip,
    successes,
    failures,
    avg_response_time_ms,
    success_latencies_json,
    errors_json
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPingCheckResultParams struct {
	CheckID              string
	ResolvedIp           string
	Successes            int64
	Failures             int64
	AvgResponseTimeMs    sql.NullFloat64
	SuccessLatenciesJson string
	ErrorsJson           sql.NullString
}

func (q *Queries) InsertPingCheckResult(ctx context.Context, arg InsertPingCheckResultParams) error {
	_, err := q.db.ExecContext(ctx, insertPingCheckResult,
		arg.CheckID,
		arg.ResolvedIp,
		arg.Successes,
		arg.Failures,
		arg.AvgResponseTimeMs,
		arg.SuccessLatenciesJson,
		arg.ErrorsJson,
	)
	return err
}

const insertPluginCheckResult = `-- name: InsertPluginCheckResult :exec
INSERT INTO check_results_plugin (
    check_id,
    plugin_name,
    plugin_version,
    success,
    response_time_ms,
    error,
    data_json
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertPluginCheckResultParams struct {
	CheckID        string
	PluginName     string
	PluginVersion  string
	Success        int64
	ResponseTimeMs sql.NullFloat64
	Error          sql.NullString
	DataJson       string
}

func (q *Queries) InsertPluginCheckResult(ctx context.Context, arg InsertPluginCheckResultParams) error {
	_, err := q.db.ExecContext(ctx, insertPluginCheckResult,
		arg.CheckID,
		arg.PluginName,
		arg.PluginVersion,
		arg.Success,
		arg.ResponseTimeMs,
		arg.Error,
		arg.DataJson,
	)
	return err
}

const insertTcpConnectCheckResult = `-- name: InsertTcpConnectCheckResult :exec
INSERT INTO check_results_tcp_connect (
    check_id,
    resolved_ip,
    connected,
    connect_time_ms,
    error
) VALUES (?, ?, ?, ?, ?)
`

type InsertTcpConnectCheckResultParams struct {
	CheckID       string
	ResolvedIp    string
	Connected     int64
	ConnectTimeMs sql.NullFloat64
	Error         sql.NullString
}

func (q *Queries) InsertTcpConnectCheckResult(ctx context.Context, arg InsertTcpConnectCheckResultParams) error {
	_, err := q.db.ExecContext(ctx, insertTcpConnectCheckResult,
		arg.CheckID,
		arg.ResolvedIp,
		arg.Connected,
		arg.ConnectTimeMs,
		arg.Error,
	)
	return err
}

const insertTracerouteCheckResult = `-- name: InsertTracerouteCheckResult :exec
INSERT INTO check_results_traceroute (
    check_id,
    target_reached,
    total_time_ms,
    errors_json
) VALUES (?, ?, ?, ?)
`

type InsertTracerouteCheckResultParams struct {
	CheckID       string
	TargetReached int64
	TotalTimeMs   sql.NullFloat64
	ErrorsJson    sql.NullString
}

func (q *Queries) InsertTracerouteCheckResult(ctx context.Context, arg InsertTracerouteCheckResultParams) error {
	_, err := q.db.ExecContext(ctx, insertTracerouteCheckResult,
		arg.CheckID,
		arg.TargetReached,
		arg.TotalTimeMs,
		arg.ErrorsJson,
	)
	return err
}

const insertTracerouteHop = `-- name: InsertTracerouteHop :exec
INSERT INTO check_results_traceroute_hops (
    id,
    check_id,
    hop,
    resolved_ip,
    hostname,
    success_latencies_json
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTracerouteHopParams struct {
	ID                   string
	CheckID              string
	Hop                  int64
	ResolvedIp           sql.NullString
	Hostname             sql.NullString
	SuccessLatenciesJson string
}

func (q *Queries) InsertTracerouteHop(ctx context.Context, arg InsertTracerouteHopParams) error {
	_, err := q.db.ExecContext(ctx, insertTracerouteHop,
		arg.ID,
		arg.CheckID,
		arg.Hop,
		arg.ResolvedIp,
		arg.Hostname,
		arg.SuccessLatenciesJson,
	)
	return err
}

const insertUdpConnectCheckResult = `-- name: InsertUdpConnectCheckResult :exec
INSERT INTO check_results_udp_connect (
    check_id,
    resolved_ip,
    probe_successful,
    response_time_ms,
    error
) VALUES (?, ?, ?, ?, ?)
`

type InsertUdpConnectCheckResultParams struct {
	CheckID         string
	ResolvedIp      string
	ProbeSuccessful int64
	ResponseTimeMs  sql.NullFloat64
	Error           sql.NullString
}

func (q *Queries) InsertUdpConnectCheckResult(ctx context.Context, arg InsertUdpConnectCheckResultParams) error {
	_, err := q.db.ExecContext(ctx, insertUdpConnectCheckResult,
		arg.CheckID,
		arg.ResolvedIp,
		arg.ProbeSuccessful,
		arg.ResponseTimeMs,
		arg.Error,
	)
	return err
}
