// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package queries

import (
	"context"
)

const lookupEndpointByAgentAndAddress = `-- name: LookupEndpointByAgentAndAddress :one
SELECT id FROM endpoints WHERE agent_id = ? AND address = ? LIMIT 1
`

type LookupEndpointByAgentAndAddressParams struct {
	AgentID string
	Address string
}

func (q *Queries) LookupEndpointByAgentAndAddress(ctx context.Context, arg LookupEndpointByAgentAndAddressParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lookupEndpointByAgentAndAddress, arg.AgentID, arg.Address)
	var id string
	err := row.Scan(&id)
	return id, err
}
