// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID            string
	SectionID     string
	Name          string
	ApiKeyHash    string
	BaseConfig    string
	ConfigVersion int64
	AgentVersion  sql.NullString
	LastSeenAt    sql.NullTime
	UpdatedAt     time.Time
	CreatedAt     time.Time
}

type AgentClaim struct {
	ID                  string
	ClaimTokenHash      string
	Hostname            string
	AgentVersion        string
	ClaimTokenExpiresAt time.Time
	PollCount           int64
	LastSeenAt          time.Time
	CreatedAt           time.Time
	ClaimedAt           sql.NullTime
	ClaimedByUserID     sql.NullString
	ApiKeyPlaintext     sql.NullString
	ApiKeyDelivered     int64
}

type AgentTag struct {
	AgentID string
	TagID   string
}

type Endpoint struct {
	ID        string
	AgentID   string
	Address   string
	Port      sql.NullInt64
	Enabled   int64
	UpdatedAt time.Time
	CreatedAt time.Time
}

type EndpointTag struct {
	EndpointID string
	TagID      string
}

type Section struct {
	ID       string
	TenantID string
	Name     string
}

type Tag struct {
	ID        string
	SectionID string
	Name      string
	Scope     string
}

type Tenant struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID            string
	TenantID      string
	OauthProvider string
	OauthSubject  string
	DisplayName   string
	LastLoginAt   sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
