// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID            string
	SectionID     string
	Name          string
	ApiKeyHash    string
	BaseConfig    string
	ConfigVersion int64
	AgentVersion  sql.NullString
	LastSeenAt    sql.NullTime
	UpdatedAt     time.Time
	CreatedAt     time.Time
}

type AgentClaim struct {
	ID                  string
	ClaimTokenHash      string
	Hostname            string
	AgentVersion        string
	ClaimTokenExpiresAt time.Time
	PollCount           int64
	LastSeenAt          time.Time
	CreatedAt           time.Time
	ClaimedAt           sql.NullTime
	ClaimedByUserID     sql.NullString
	ApiKeyPlaintext     sql.NullString
	ApiKeyDelivered     int64
}

type AgentTag struct {
	AgentID string
	TagID   string
}

type CheckResult struct {
	ID            string
	AgentID       string
	EndpointID    sql.NullString
	CheckType     string
	TargetAddress string
	TargetPort    sql.NullInt64
	Success       int64
	CheckedAt     time.Time
	ReceivedAt    time.Time
}

type Endpoint struct {
	ID        string
	AgentID   string
	Address   string
	Port      sql.NullInt64
	Enabled   int64
	UpdatedAt time.Time
	CreatedAt time.Time
}

type EndpointTag struct {
	EndpointID string
	TagID      string
}

type HttpGetCheckResult struct {
	CheckID           string
	StatusCode        int64
	ResponseTimeMs    sql.NullFloat64
	ResponseSizeBytes sql.NullInt64
	Error             sql.NullString
}

type PingCheckResult struct {
	CheckID              string
	ResolvedIp           string
	Successes            int64
	Failures             int64
	AvgResponseTimeMs    sql.NullFloat64
	SuccessLatenciesJson string
	ErrorsJson           sql.NullString
}

type PluginCheckResult struct {
	CheckID        string
	PluginName     string
	PluginVersion  string
	Success        int64
	ResponseTimeMs sql.NullFloat64
	Error          sql.NullString
	DataJson       string
}

type Section struct {
	ID       string
	TenantID string
	Name     string
}

type Tag struct {
	ID        string
	SectionID string
	Name      string
	Scope     string
}

type TcpConnectCheckResult struct {
	CheckID       string
	ResolvedIp    string
	Connected     int64
	ConnectTimeMs sql.NullFloat64
	Error         sql.NullString
}

type Tenant struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type TracerouteCheckResult struct {
	CheckID       string
	TargetReached int64
	TotalTimeMs   sql.NullFloat64
	ErrorsJson    sql.NullString
}

type TracerouteHop struct {
	ID             string
	CheckID        string
	Hop            int64
	Address        sql.NullString
	Hostname       sql.NullString
	ResponseTimeMs sql.NullFloat64
}

type UdpConnectCheckResult struct {
	CheckID         string
	ResolvedIp      string
	ProbeSuccessful int64
	ResponseTimeMs  sql.NullFloat64
	Error           sql.NullString
}

type User struct {
	ID            string
	TenantID      string
	OauthProvider string
	OauthSubject  string
	DisplayName   string
	LastLoginAt   sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
