// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Agent struct {
	ID         string
	SectionID  string
	Name       string
	ApiKeyHash string
	BaseConfig string
	Version    int64
	LastSeenAt sql.NullString
	UpdatedAt  string
	CreatedAt  string
}

type AgentTag struct {
	AgentID string
	TagID   string
}

type Endpoint struct {
	ID        string
	AgentID   string
	Address   string
	Enabled   int64
	UpdatedAt string
	CreatedAt string
}

type EndpointTag struct {
	EndpointID string
	TagID      string
}

type Section struct {
	ID       string
	TenantID string
	Name     string
}

type Tag struct {
	ID        string
	SectionID string
	Name      string
	Scope     string
}

type Tenant struct {
	ID        string
	Name      string
	CreatedAt string
}
