// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: topologies.sql

package queries

import (
	"context"
)

const addTopologyMember = `-- name: AddTopologyMember :exec
INSERT INTO topology_members (topology_id, tag_id, role)
VALUES (?, ?, ?)
`

type AddTopologyMemberParams struct {
	TopologyID string
	TagID      string
	Role       string
}

func (q *Queries) AddTopologyMember(ctx context.Context, arg AddTopologyMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTopologyMember, arg.TopologyID, arg.TagID, arg.Role)
	return err
}

const createTopology = `-- name: CreateTopology :one
INSERT INTO topologies (id, section_id, name, type, enabled)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateTopologyParams struct {
	ID        string
	SectionID string
	Name      string
	Type      string
	Enabled   int64
}

func (q *Queries) CreateTopology(ctx context.Context, arg CreateTopologyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createTopology,
		arg.ID,
		arg.SectionID,
		arg.Name,
		arg.Type,
		arg.Enabled,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteTopology = `-- name: DeleteTopology :exec
DELETE FROM topologies WHERE id = ?
`

func (q *Queries) DeleteTopology(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTopology, id)
	return err
}

const getTopology = `-- name: GetTopology :one
SELECT id, section_id, name, type, enabled, updated_at, created_at
FROM topologies
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetTopology(ctx context.Context, id string) (Topology, error) {
	row := q.db.QueryRowContext(ctx, getTopology, id)
	var i Topology
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTopologiesBySection = `-- name: ListTopologiesBySection :many
SELECT id, section_id, name, type, enabled, updated_at, created_at
FROM topologies
WHERE section_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTopologiesBySection(ctx context.Context, sectionID string) ([]Topology, error) {
	rows, err := q.db.QueryContext(ctx, listTopologiesBySection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topology
	for rows.Next() {
		var i Topology
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopologyMembers = `-- name: ListTopologyMembers :many
SELECT tm.topology_id, tm.tag_id, tm.role, t.name AS tag_name
FROM topology_members tm
JOIN tags t ON t.id = tm.tag_id
WHERE tm.topology_id = ?
ORDER BY tm.role, t.name
`

type ListTopologyMembersRow struct {
	TopologyID string
	TagID      string
	Role       string
	TagName    string
}

func (q *Queries) ListTopologyMembers(ctx context.Context, topologyID string) ([]ListTopologyMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopologyMembers, topologyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopologyMembersRow
	for rows.Next() {
		var i ListTopologyMembersRow
		if err := rows.Scan(
			&i.TopologyID,
			&i.TagID,
			&i.Role,
			&i.TagName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTopologyMember = `-- name: RemoveTopologyMember :exec
DELETE FROM topology_members
WHERE topology_id = ? AND tag_id = ? AND role = ?
`

type RemoveTopologyMemberParams struct {
	TopologyID string
	TagID      string
	Role       string
}

func (q *Queries) RemoveTopologyMember(ctx context.Context, arg RemoveTopologyMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTopologyMember, arg.TopologyID, arg.TagID, arg.Role)
	return err
}

const updateTopology = `-- name: UpdateTopology :exec
UPDATE topologies
SET name = ?, type = ?, enabled = ?
WHERE id = ?
`

type UpdateTopologyParams struct {
	Name    string
	Type    string
	Enabled int64
	ID      string
}

func (q *Queries) UpdateTopology(ctx context.Context, arg UpdateTopologyParams) error {
	_, err := q.db.ExecContext(ctx, updateTopology,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.ID,
	)
	return err
}
