// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    tenant_id,
    oauth_provider,
    oauth_subject,
    display_name
) VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateUserParams struct {
	ID            string
	TenantID      string
	OauthProvider string
	OauthSubject  string
	DisplayName   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.OauthProvider,
		arg.OauthSubject,
		arg.DisplayName,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, oauth_provider, oauth_subject, display_name, last_login_at, created_at, updated_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.DisplayName,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT id, tenant_id, oauth_provider, oauth_subject, display_name, last_login_at, created_at, updated_at FROM users
WHERE oauth_provider = ? AND oauth_subject = ?
LIMIT 1
`

type GetUserByOAuthParams struct {
	OauthProvider string
	OauthSubject  string
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOAuth, arg.OauthProvider, arg.OauthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OauthProvider,
		&i.OauthSubject,
		&i.DisplayName,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, oauth_provider, oauth_subject, display_name, last_login_at, created_at, updated_at FROM users
WHERE tenant_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OauthProvider,
			&i.OauthSubject,
			&i.DisplayName,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users
SET display_name = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateUserDisplayNameParams struct {
	DisplayName string
	ID          string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDisplayName, arg.DisplayName, arg.ID)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = datetime('now')
WHERE id = ?
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}

const upsertUserByOAuth = `-- name: UpsertUserByOAuth :one
INSERT INTO users (
    id,
    tenant_id,
    oauth_provider,
    oauth_subject,
    display_name,
    last_login_at
) VALUES (?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(oauth_provider, oauth_subject) DO UPDATE SET
    display_name = COALESCE(excluded.display_name, display_name),
    last_login_at = datetime('now'),
    updated_at = datetime('now')
RETURNING id
`

type UpsertUserByOAuthParams struct {
	ID            string
	TenantID      string
	OauthProvider string
	OauthSubject  string
	DisplayName   string
}

// Creates or updates user on OAuth login
func (q *Queries) UpsertUserByOAuth(ctx context.Context, arg UpsertUserByOAuthParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByOAuth,
		arg.ID,
		arg.TenantID,
		arg.OauthProvider,
		arg.OauthSubject,
		arg.DisplayName,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
