// Package api_v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api_v1

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AgentApiKeyScopes             = "AgentApiKey.Scopes"
	OAuth2AuthorizationCodeScopes = "OAuth2AuthorizationCode.Scopes"
	OAuth2ClientCredentialsScopes = "OAuth2ClientCredentials.Scopes"
)

// Defines values for AgentHealthStatus.
const (
	Degraded AgentHealthStatus = "degraded"
	Healthy  AgentHealthStatus = "healthy"
)

// Defines values for ClaimResponseStatus.
const (
	ClaimResponseStatusClaimed ClaimResponseStatus = "claimed"
)

// Defines values for ClaimStatusClaimedEnum.
const (
	ClaimStatusClaimedEnumClaimed ClaimStatusClaimedEnum = "claimed"
)

// Defines values for ClaimStatusPendingEnum.
const (
	ClaimStatusPendingEnumPendingClaim ClaimStatusPendingEnum = "pending_claim"
)

// Defines values for HttpGetCheckType.
const (
	Httpget HttpGetCheckType = "httpget"
)

// Defines values for IpAddressFamily.
const (
	Ipv4 IpAddressFamily = "ipv4"
	Ipv6 IpAddressFamily = "ipv6"
)

// Defines values for PingCheckType.
const (
	Ping PingCheckType = "ping"
)

// Defines values for PluginCheckType.
const (
	Plugin PluginCheckType = "plugin"
)

// Defines values for RegistrationStatus.
const (
	RegistrationStatusPendingClaim RegistrationStatus = "pending_claim"
)

// Defines values for TcpConnectCheckType.
const (
	Tcpconnect TcpConnectCheckType = "tcpconnect"
)

// Defines values for TracerouteCheckType.
const (
	Traceroute TracerouteCheckType = "traceroute"
)

// Defines values for UdpConnectCheckType.
const (
	Udpconnect UdpConnectCheckType = "udpconnect"
)

// Defines values for Oauth2AuthorizeParamsCodeChallengeMethod.
const (
	S256 Oauth2AuthorizeParamsCodeChallengeMethod = "S256"
)

// Defines values for Oauth2TokenFormdataBodyGrantType.
const (
	AuthorizationCode Oauth2TokenFormdataBodyGrantType = "authorization_code"
)

// Agent defines model for Agent.
type Agent struct {
	// AgentVersion Version of the agent software, null if not yet reported
	AgentVersion *string `json:"agentVersion"`

	// ConfigVersion Current configuration version
	ConfigVersion int `json:"configVersion"`

	// CreatedAt Timestamp when the agent was registered
	CreatedAt time.Time `json:"createdAt"`

	// Id UUID version 7 as per RFC 4122
	Id UUIDv7 `json:"id"`

	// IpAddresses Network interfaces reported by the agent
	IpAddresses *[]AgentNetworkInterface `json:"ipAddresses,omitempty"`

	// LastResultSubmittedAt Timestamp of the last monitoring result submission
	LastResultSubmittedAt *time.Time `json:"lastResultSubmittedAt"`

	// LastSeenAt Timestamp of the last heartbeat received from the agent
	LastSeenAt *time.Time `json:"lastSeenAt"`

	// Name Human-readable agent name
	Name string `json:"name"`

	// SectionId Section (organizational unit) this agent belongs to
	SectionId string `json:"sectionId"`

	// UpdatedAt Timestamp when the agent record was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// AgentConfig defines model for AgentConfig.
type AgentConfig struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agent_id"`

	// AgentName Human-readable agent name
	AgentName string `json:"agent_name"`

	// Endpoints Endpoints to monitor
	Endpoints  []Endpoint       `json:"endpoints"`
	Monitoring MonitoringConfig `json:"monitoring"`
	Server     ServerConfig     `json:"server"`
	Storage    StorageConfig    `json:"storage"`

	// Tags Tags for this agent (used for mesh organization)
	Tags *[]string `json:"tags,omitempty"`

	// Version Configuration version (used for syncing with server)
	Version int32 `json:"version"`
}

// AgentHealthStatus Health status of the agent
type AgentHealthStatus string

// AgentHeartbeat defines model for AgentHeartbeat.
type AgentHeartbeat struct {
	// CpuUsagePercent CPU utilization percentage (0.0–100.0)
	CpuUsagePercent float32 `json:"cpu_usage_percent"`

	// MemoryTotalMb Total physical memory available (MB)
	MemoryTotalMb float32 `json:"memory_total_mb"`

	// MemoryUsageMb Resident memory currently in use (MB)
	MemoryUsageMb float32 `json:"memory_usage_mb"`

	// Status Health status of the agent
	Status AgentHealthStatus `json:"status"`

	// SystemUptimeSecs System uptime in seconds
	SystemUptimeSecs int64 `json:"system_uptime_secs"`

	// Timestamp Agent-local timestamp when the heartbeat was generated (RFC3339)
	Timestamp time.Time `json:"timestamp"`
}

// AgentListResponse defines model for AgentListResponse.
type AgentListResponse struct {
	Agents     []Agent    `json:"agents"`
	Pagination Pagination `json:"pagination"`
}

// AgentNetworkInterface defines model for AgentNetworkInterface.
type AgentNetworkInterface struct {
	// Family IP address family (IPv4 or IPv6)
	Family IpAddressFamily `json:"family"`

	// Iface Name of the network interface
	Iface string `json:"iface"`

	// Ip IP address of the network interface (IPv4 or IPv6, excluding loopback and link-local)
	Ip string `json:"ip"`

	// Recommended Whether this address is recommended for the server to use when communicating
	// with the agent. Determined by the agent using the OS routing table: the source
	// IP the OS selects when opening a connection toward the server is marked as
	// recommended. Only one entry will have recommended=true.
	Recommended bool `json:"recommended"`
}

// AgentRegistrationResponse defines model for AgentRegistrationResponse.
type AgentRegistrationResponse struct {
	// ClaimUrl URL for user to claim the agent (web UI)
	ClaimUrl string `json:"claimUrl"`

	// ExpiresAt When the claim token expires (RFC3339)
	ExpiresAt time.Time `json:"expiresAt"`

	// PollUrl URL for agent to poll for claim status
	PollUrl string `json:"pollUrl"`

	// Status Status of agent registration
	Status RegistrationStatus `json:"status"`
}

// AgentSelfRegistration defines model for AgentSelfRegistration.
type AgentSelfRegistration struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agentId"`

	// AgentVersion Version of the agent software
	AgentVersion string `json:"agentVersion"`

	// ClaimTokenHash SHA-256 hash of the claim token (plain token shown in agent logs for user)
	ClaimTokenHash string `json:"claimTokenHash"`

	// Hostname System hostname of the machine running the agent
	Hostname string `json:"hostname"`

	// IpAddresses List of all non-loopback, non-link-local network interfaces on the agent host.
	// Loopback (127.x.x.x / ::1) and link-local (169.254.x.x / fe80::/10) addresses
	// are excluded. The server should store all addresses and allow the operator to
	// select the preferred one during the claim process. The entry with
	// recommended=true reflects the OS-selected source IP for connections toward
	// the server (determined via routing table, no traffic sent).
	IpAddresses []AgentNetworkInterface `json:"ipAddresses"`
}

// BatchMonitoringResults A batch of monitoring results submitted by an agent from its local cache.
// The server deduplicates entries by `MonitoringResult.id`.
type BatchMonitoringResults struct {
	// Results Ordered list of monitoring results (oldest-first)
	Results []MonitoringResult `json:"results"`
}

// CheckType defines model for CheckType.
type CheckType struct {
	union json.RawMessage
}

// ClaimAgentRequest defines model for ClaimAgentRequest.
type ClaimAgentRequest struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agentId"`

	// ClaimToken Claim token from agent logs
	ClaimToken string `json:"claimToken"`

	// Name Human-readable name for the agent (defaults to hostname if not provided)
	Name *string `json:"name,omitempty"`

	// SectionId UUID version 7 as per RFC 4122
	SectionId UUIDv7 `json:"sectionId"`
}

// ClaimAgentResponse defines model for ClaimAgentResponse.
type ClaimAgentResponse struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agentId"`

	// Message Human-readable message
	Message string `json:"message"`

	// Status Status in claim response
	Status ClaimResponseStatus `json:"status"`
}

// ClaimResponseStatus Status in claim response
type ClaimResponseStatus string

// ClaimStatusClaimed defines model for ClaimStatusClaimed.
type ClaimStatusClaimed struct {
	// ApiKey API key for authenticated requests (one-time delivery)
	ApiKey string `json:"apiKey"`

	// ConfigUrl URL to fetch agent configuration
	ConfigUrl string `json:"configUrl"`

	// Status Claimed status
	Status ClaimStatusClaimedEnum `json:"status"`
}

// ClaimStatusClaimedEnum Claimed status
type ClaimStatusClaimedEnum string

// ClaimStatusPending defines model for ClaimStatusPending.
type ClaimStatusPending struct {
	// ExpiresAt When the claim token expires (RFC3339)
	ExpiresAt time.Time `json:"expiresAt"`

	// PollIn Seconds until next poll (server-controlled backoff)
	PollIn int32 `json:"pollIn"`

	// Status Pending claim status
	Status ClaimStatusPendingEnum `json:"status"`
}

// ClaimStatusPendingEnum Pending claim status
type ClaimStatusPendingEnum string

// Endpoint An endpoint to monitor (IP address, hostname, or URL)
type Endpoint struct {
	// Address IP address, hostname, or URL
	Address string `json:"address"`
	Enabled bool   `json:"enabled"`

	// Id UUID version 7 as per RFC 4122
	Id   UUIDv7 `json:"id"`
	Port *int   `json:"port,omitempty"`

	// Tags Tags associated with the target
	Tags []string `json:"tags"`
}

// Error defines model for Error.
type Error struct {
	Details *[]struct {
		Field *string `json:"field,omitempty"`
		Issue *string `json:"issue,omitempty"`
	} `json:"details,omitempty"`

	// DocumentationUrl Link to relevant documentation
	DocumentationUrl *string             `json:"documentation_url,omitempty"`
	Error            string              `json:"error"`
	Message          string              `json:"message"`
	RequestId        *openapi_types.UUID `json:"request_id,omitempty"`
}

// ErrorDetails Error information from a check, stored as an extensible JSON object
type ErrorDetails struct {
	// Errors List of error messages from the check
	Errors *[]string `json:"errors,omitempty"`
}

// HttpGetCheck defines model for HttpGetCheck.
type HttpGetCheck struct {
	Result HttpGetResult    `json:"result"`
	Type   HttpGetCheckType `json:"type"`
}

// HttpGetCheckType defines model for HttpGetCheckType.
type HttpGetCheckType string

// HttpGetResult defines model for HttpGetResult.
type HttpGetResult struct {
	// ErrorDetails Error information from a check, stored as an extensible JSON object
	ErrorDetails      *ErrorDetails `json:"error_details"`
	ResponseSizeBytes *int64        `json:"response_size_bytes"`
	ResponseTimeMs    *float64      `json:"response_time_ms"`
	StatusCode        int32         `json:"status_code"`
	Success           bool          `json:"success"`
}

// IpAddressFamily IP address family (IPv4 or IPv6)
type IpAddressFamily string

// MonitoringConfig defines model for MonitoringConfig.
type MonitoringConfig struct {
	// IntervalSecs Interval between checks in seconds
	IntervalSecs int64 `json:"interval_secs"`

	// MaxConcurrent Maximum number of concurrent checks
	MaxConcurrent int `json:"max_concurrent"`

	// PingCount Number of pings to send per check
	PingCount int32 `json:"ping_count"`

	// TimeoutSecs Timeout for each check in seconds
	TimeoutSecs int64 `json:"timeout_secs"`

	// TracerouteMaxHops Maximum TTL for traceroute
	TracerouteMaxHops int32 `json:"traceroute_max_hops"`

	// TracerouteOnFailure Enable traceroute on failed pings
	TracerouteOnFailure bool `json:"traceroute_on_failure"`
}

// MonitoringResult defines model for MonitoringResult.
type MonitoringResult struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId   UUIDv7    `json:"agent_id"`
	CheckType CheckType `json:"check_type"`

	// EndpointId UUID version 7 as per RFC 4122
	EndpointId UUIDv7 `json:"endpoint_id"`

	// Id UUID version 7 as per RFC 4122
	Id UUIDv7 `json:"id"`

	// Timestamp Timestamp when the report was generated (RFC3339)
	Timestamp time.Time `json:"timestamp"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	HasNext     *bool `json:"has_next,omitempty"`
	HasPrevious *bool `json:"has_previous,omitempty"`
	Page        int   `json:"page"`
	PageSize    int   `json:"page_size"`
	TotalItems  int   `json:"total_items"`
	TotalPages  int   `json:"total_pages"`
}

// PingCheck defines model for PingCheck.
type PingCheck struct {
	Result PingResult    `json:"result"`
	Type   PingCheckType `json:"type"`
}

// PingCheckType defines model for PingCheckType.
type PingCheckType string

// PingResult defines model for PingResult.
type PingResult struct {
	// ErrorDetails Error information from a check, stored as an extensible JSON object
	ErrorDetails *ErrorDetails `json:"error_details"`
	Failures     int32         `json:"failures"`

	// ResolvedIp Resolved IP address of the target
	ResolvedIp       string    `json:"resolved_ip"`
	SuccessLatencies []float64 `json:"success_latencies"`
	Successes        int32     `json:"successes"`
}

// PluginCheck defines model for PluginCheck.
type PluginCheck struct {
	Result PluginResult    `json:"result"`
	Type   PluginCheckType `json:"type"`
}

// PluginCheckType defines model for PluginCheckType.
type PluginCheckType string

// PluginResult defines model for PluginResult.
type PluginResult struct {
	Data map[string]string `json:"data"`

	// ErrorDetails Error information from a check, stored as an extensible JSON object
	ErrorDetails   *ErrorDetails `json:"error_details"`
	PluginName     string        `json:"plugin_name"`
	PluginVersion  string        `json:"plugin_version"`
	ResponseTimeMs *float64      `json:"response_time_ms"`
	Success        bool          `json:"success"`
}

// RegistrationStatus Status of agent registration
type RegistrationStatus string

// ResultsBatchAcknowledgment defines model for ResultsBatchAcknowledgment.
type ResultsBatchAcknowledgment struct {
	// Accepted Number of results accepted for processing
	Accepted int `json:"accepted"`

	// DuplicatesSkipped Number of results deduplicated (already known to the server)
	DuplicatesSkipped *int `json:"duplicates_skipped,omitempty"`

	// ReceivedAt Timestamp when the batch was received by the server
	ReceivedAt time.Time `json:"received_at"`

	// SubmissionId UUID version 7 as per RFC 4122
	SubmissionId UUIDv7 `json:"submission_id"`
}

// ServerConfig defines model for ServerConfig.
type ServerConfig struct {
	// ApiKey API key for authentication
	ApiKey *string `json:"api_key"`

	// HeartbeatIntervalSecs Heartbeat interval in seconds
	HeartbeatIntervalSecs int64 `json:"heartbeat_interval_secs"`

	// ReportIntervalSecs Report interval in seconds
	ReportIntervalSecs int64 `json:"report_interval_secs"`

	// RetryAttempts Retry attempts on failure
	RetryAttempts int32 `json:"retry_attempts"`

	// TimeoutSecs Connection timeout in seconds
	TimeoutSecs int64 `json:"timeout_secs"`

	// Url Server URL
	Url *string `json:"url"`

	// VerifyTls Enable TLS verification
	VerifyTls bool `json:"verify_tls"`
}

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// CacheDir Directory for storing cached data
	CacheDir string `json:"cache_dir"`

	// MaxCacheAgeSecs Maximum age of cached results in seconds (e.g., 86400 = 24 hours)
	MaxCacheAgeSecs int64 `json:"max_cache_age_secs"`

	// MaxCachedResults Maximum number of results to cache
	MaxCachedResults int `json:"max_cached_results"`
}

// TcpConnectCheck defines model for TcpConnectCheck.
type TcpConnectCheck struct {
	Result TcpConnectResult    `json:"result"`
	Type   TcpConnectCheckType `json:"type"`
}

// TcpConnectCheckType defines model for TcpConnectCheckType.
type TcpConnectCheckType string

// TcpConnectResult defines model for TcpConnectResult.
type TcpConnectResult struct {
	ConnectTimeMs *float64 `json:"connect_time_ms"`
	Connected     bool     `json:"connected"`

	// ErrorDetails Error information from a check, stored as an extensible JSON object
	ErrorDetails *ErrorDetails `json:"error_details"`
	ResolvedIp   string        `json:"resolved_ip"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// ExpiresAt Hard expiry time (ISO 8601). The session will never be valid after
	// this timestamp regardless of activity. Use this to schedule a
	// proactive re-login in the client (e.g. at the midpoint).
	ExpiresAt time.Time `json:"expires_at"`

	// OpaqueToken Server-managed opaque session token. Use as a Bearer token in the
	// Authorization header for all subsequent requests.
	// Format: st_live_<hex> (production) or st_test_<hex> (dev/test).
	OpaqueToken string `json:"opaque_token"`
}

// TracerouteCheck defines model for TracerouteCheck.
type TracerouteCheck struct {
	Result TracerouteResult    `json:"result"`
	Type   TracerouteCheckType `json:"type"`
}

// TracerouteCheckType defines model for TracerouteCheckType.
type TracerouteCheckType string

// TracerouteHop defines model for TracerouteHop.
type TracerouteHop struct {
	Hop      int32   `json:"hop"`
	Hostname *string `json:"hostname,omitempty"`

	// ResolvedIp Resolved IP address of the target
	ResolvedIp       *string    `json:"resolved_ip,omitempty"`
	SuccessLatencies *[]float64 `json:"success_latencies,omitempty"`
}

// TracerouteResult defines model for TracerouteResult.
type TracerouteResult struct {
	// ErrorDetails Error information from a check, stored as an extensible JSON object
	ErrorDetails  *ErrorDetails   `json:"error_details"`
	Hops          []TracerouteHop `json:"hops"`
	TargetReached bool            `json:"target_reached"`
}

// UUIDv7 UUID version 7 as per RFC 4122
type UUIDv7 = uuid.UUID

// UdpConnectCheck defines model for UdpConnectCheck.
type UdpConnectCheck struct {
	Result UdpConnectResult    `json:"result"`
	Type   UdpConnectCheckType `json:"type"`
}

// UdpConnectCheckType defines model for UdpConnectCheckType.
type UdpConnectCheckType string

// UdpConnectResult defines model for UdpConnectResult.
type UdpConnectResult struct {
	// ErrorDetails Error information from a check, stored as an extensible JSON object
	ErrorDetails    *ErrorDetails `json:"error_details"`
	ProbeSuccessful bool          `json:"probe_successful"`
	ResolvedIp      string        `json:"resolved_ip"`
	ResponseTimeMs  *float64      `json:"response_time_ms"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email          *openapi_types.Email `json:"email,omitempty"`
	EmailVerified  *bool                `json:"email_verified,omitempty"`
	FamilyName     *string              `json:"family_name,omitempty"`
	GivenName      *string              `json:"given_name,omitempty"`
	Name           *string              `json:"name,omitempty"`
	OrganizationId *openapi_types.UUID  `json:"organization_id,omitempty"`
	Permissions    *[]string            `json:"permissions,omitempty"`
	Picture        *string              `json:"picture,omitempty"`
	Roles          *[]string            `json:"roles,omitempty"`

	// Sub Subject identifier (user ID)
	Sub string `json:"sub"`
}

// AgentId UUID version 7 as per RFC 4122
type AgentId = UUIDv7

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// NotImplemented defines model for NotImplemented.
type NotImplemented = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	// Page Page number (1-based)
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Number of agents per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// LogoutJSONBody defines parameters for Logout.
type LogoutJSONBody struct {
	// PostLogoutRedirectUri Optional URI to redirect to after IDP logout completes.
	// Forwarded to the IDP end-session endpoint as post_logout_redirect_uri.
	PostLogoutRedirectUri *string `json:"post_logout_redirect_uri,omitempty"`
}

// Oauth2AuthorizeParams defines parameters for Oauth2Authorize.
type Oauth2AuthorizeParams struct {
	// Provider Identity provider name. Must match a provider configured on the server.
	// Built-in values: okta, auth0, azure, google, github.
	Provider string `form:"provider" json:"provider"`

	// Scope Space-separated list of requested scopes
	Scope string `form:"scope" json:"scope"`

	// State CSRF protection token generated by the client
	State string `form:"state" json:"state"`

	// CodeChallenge PKCE code challenge (BASE64URL(SHA256(code_verifier)))
	CodeChallenge string `form:"code_challenge" json:"code_challenge"`

	// CodeChallengeMethod PKCE code challenge method — must be S256
	CodeChallengeMethod Oauth2AuthorizeParamsCodeChallengeMethod `form:"code_challenge_method" json:"code_challenge_method"`
}

// Oauth2AuthorizeParamsCodeChallengeMethod defines parameters for Oauth2Authorize.
type Oauth2AuthorizeParamsCodeChallengeMethod string

// Oauth2CallbackParams defines parameters for Oauth2Callback.
type Oauth2CallbackParams struct {
	// Code Authorization code issued by the identity provider
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State CSRF protection token (must match the original authorize request)
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Error code if authorization failed at the IDP
	Error *string `form:"error,omitempty" json:"error,omitempty"`

	// ErrorDescription Human-readable error description from the IDP
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// Oauth2RevokeJSONBody defines parameters for Oauth2Revoke.
type Oauth2RevokeJSONBody struct {
	// OpaqueToken The opaque session token to revoke (as returned by /auth/oauth2/token or /auth/refresh)
	OpaqueToken string `json:"opaque_token"`
}

// Oauth2TokenFormdataBody defines parameters for Oauth2Token.
type Oauth2TokenFormdataBody struct {
	// Code Authorization code returned by the IDP callback
	Code string `form:"code" json:"code"`

	// CodeVerifier PKCE code verifier corresponding to the code_challenge sent at /authorize
	CodeVerifier string `form:"code_verifier" json:"code_verifier"`

	// GrantType OAuth2 grant type (only authorization_code is supported here)
	GrantType Oauth2TokenFormdataBodyGrantType `form:"grant_type" json:"grant_type"`

	// RedirectUri Must exactly match the redirect_uri used in the authorization request
	RedirectUri string `form:"redirect_uri" json:"redirect_uri"`
}

// Oauth2TokenFormdataBodyGrantType defines parameters for Oauth2Token.
type Oauth2TokenFormdataBodyGrantType string

// PostClaimAgentJSONRequestBody defines body for PostClaimAgent for application/json ContentType.
type PostClaimAgentJSONRequestBody = ClaimAgentRequest

// RegisterAgentSelfJSONRequestBody defines body for RegisterAgentSelf for application/json ContentType.
type RegisterAgentSelfJSONRequestBody = AgentSelfRegistration

// SendAgentHeartbeatJSONRequestBody defines body for SendAgentHeartbeat for application/json ContentType.
type SendAgentHeartbeatJSONRequestBody = AgentHeartbeat

// SubmitAgentResultsJSONRequestBody defines body for SubmitAgentResults for application/json ContentType.
type SubmitAgentResultsJSONRequestBody = BatchMonitoringResults

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody LogoutJSONBody

// Oauth2RevokeJSONRequestBody defines body for Oauth2Revoke for application/json ContentType.
type Oauth2RevokeJSONRequestBody Oauth2RevokeJSONBody

// Oauth2TokenFormdataRequestBody defines body for Oauth2Token for application/x-www-form-urlencoded ContentType.
type Oauth2TokenFormdataRequestBody Oauth2TokenFormdataBody

// AsPingCheck returns the union data inside the CheckType as a PingCheck
func (t CheckType) AsPingCheck() (PingCheck, error) {
	var body PingCheck
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPingCheck overwrites any union data inside the CheckType as the provided PingCheck
func (t *CheckType) FromPingCheck(v PingCheck) error {
	v.Type = "ping"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePingCheck performs a merge with any union data inside the CheckType, using the provided PingCheck
func (t *CheckType) MergePingCheck(v PingCheck) error {
	v.Type = "ping"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTracerouteCheck returns the union data inside the CheckType as a TracerouteCheck
func (t CheckType) AsTracerouteCheck() (TracerouteCheck, error) {
	var body TracerouteCheck
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTracerouteCheck overwrites any union data inside the CheckType as the provided TracerouteCheck
func (t *CheckType) FromTracerouteCheck(v TracerouteCheck) error {
	v.Type = "traceroute"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTracerouteCheck performs a merge with any union data inside the CheckType, using the provided TracerouteCheck
func (t *CheckType) MergeTracerouteCheck(v TracerouteCheck) error {
	v.Type = "traceroute"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTcpConnectCheck returns the union data inside the CheckType as a TcpConnectCheck
func (t CheckType) AsTcpConnectCheck() (TcpConnectCheck, error) {
	var body TcpConnectCheck
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTcpConnectCheck overwrites any union data inside the CheckType as the provided TcpConnectCheck
func (t *CheckType) FromTcpConnectCheck(v TcpConnectCheck) error {
	v.Type = "tcpconnect"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTcpConnectCheck performs a merge with any union data inside the CheckType, using the provided TcpConnectCheck
func (t *CheckType) MergeTcpConnectCheck(v TcpConnectCheck) error {
	v.Type = "tcpconnect"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUdpConnectCheck returns the union data inside the CheckType as a UdpConnectCheck
func (t CheckType) AsUdpConnectCheck() (UdpConnectCheck, error) {
	var body UdpConnectCheck
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUdpConnectCheck overwrites any union data inside the CheckType as the provided UdpConnectCheck
func (t *CheckType) FromUdpConnectCheck(v UdpConnectCheck) error {
	v.Type = "udpconnect"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUdpConnectCheck performs a merge with any union data inside the CheckType, using the provided UdpConnectCheck
func (t *CheckType) MergeUdpConnectCheck(v UdpConnectCheck) error {
	v.Type = "udpconnect"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHttpGetCheck returns the union data inside the CheckType as a HttpGetCheck
func (t CheckType) AsHttpGetCheck() (HttpGetCheck, error) {
	var body HttpGetCheck
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHttpGetCheck overwrites any union data inside the CheckType as the provided HttpGetCheck
func (t *CheckType) FromHttpGetCheck(v HttpGetCheck) error {
	v.Type = "httpget"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHttpGetCheck performs a merge with any union data inside the CheckType, using the provided HttpGetCheck
func (t *CheckType) MergeHttpGetCheck(v HttpGetCheck) error {
	v.Type = "httpget"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPluginCheck returns the union data inside the CheckType as a PluginCheck
func (t CheckType) AsPluginCheck() (PluginCheck, error) {
	var body PluginCheck
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPluginCheck overwrites any union data inside the CheckType as the provided PluginCheck
func (t *CheckType) FromPluginCheck(v PluginCheck) error {
	v.Type = "plugin"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePluginCheck performs a merge with any union data inside the CheckType, using the provided PluginCheck
func (t *CheckType) MergePluginCheck(v PluginCheck) error {
	v.Type = "plugin"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CheckType) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CheckType) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "httpget":
		return t.AsHttpGetCheck()
	case "ping":
		return t.AsPingCheck()
	case "plugin":
		return t.AsPluginCheck()
	case "tcpconnect":
		return t.AsTcpConnectCheck()
	case "traceroute":
		return t.AsTracerouteCheck()
	case "udpconnect":
		return t.AsUdpConnectCheck()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CheckType) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CheckType) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Claim an agent (Web UI)
	// (POST /agent/claim)
	PostClaimAgent(w http.ResponseWriter, r *http.Request)
	// Agent self-registration (unclaimed)
	// (POST /agent/register)
	RegisterAgentSelf(w http.ResponseWriter, r *http.Request)
	// Check agent claim status (polling endpoint)
	// (GET /agent/{agentId}/claim-status)
	GetAgentClaimStatus(w http.ResponseWriter, r *http.Request, agentId AgentId)
	// Get agent configuration
	// (GET /agent/{agentId}/configuration)
	GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId)
	// Send agent heartbeat
	// (POST /agent/{agentId}/heartbeat)
	SendAgentHeartbeat(w http.ResponseWriter, r *http.Request, agentId AgentId)
	// Submit batch monitoring results
	// (POST /agent/{agentId}/results)
	SubmitAgentResults(w http.ResponseWriter, r *http.Request, agentId AgentId)
	// List agents
	// (GET /agents)
	ListAgents(w http.ResponseWriter, r *http.Request, params ListAgentsParams)
	// User logout
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// OAuth2 authorization endpoint
	// (GET /auth/oauth2/authorize)
	Oauth2Authorize(w http.ResponseWriter, r *http.Request, params Oauth2AuthorizeParams)
	// OAuth2 callback endpoint
	// (GET /auth/oauth2/callback)
	Oauth2Callback(w http.ResponseWriter, r *http.Request, params Oauth2CallbackParams)
	// Revoke a server-managed session token
	// (POST /auth/oauth2/revoke)
	Oauth2Revoke(w http.ResponseWriter, r *http.Request)
	// Exchange authorization code for a server-managed session token
	// (POST /auth/oauth2/token)
	Oauth2Token(w http.ResponseWriter, r *http.Request)
	// Refresh a server-managed session token
	// (POST /auth/refresh)
	AuthRefresh(w http.ResponseWriter, r *http.Request)
	// Get current user information
	// (GET /auth/userinfo)
	GetUserInfo(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Claim an agent (Web UI)
// (POST /agent/claim)
func (_ Unimplemented) PostClaimAgent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Agent self-registration (unclaimed)
// (POST /agent/register)
func (_ Unimplemented) RegisterAgentSelf(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check agent claim status (polling endpoint)
// (GET /agent/{agentId}/claim-status)
func (_ Unimplemented) GetAgentClaimStatus(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get agent configuration
// (GET /agent/{agentId}/configuration)
func (_ Unimplemented) GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send agent heartbeat
// (POST /agent/{agentId}/heartbeat)
func (_ Unimplemented) SendAgentHeartbeat(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit batch monitoring results
// (POST /agent/{agentId}/results)
func (_ Unimplemented) SubmitAgentResults(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List agents
// (GET /agents)
func (_ Unimplemented) ListAgents(w http.ResponseWriter, r *http.Request, params ListAgentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User logout
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OAuth2 authorization endpoint
// (GET /auth/oauth2/authorize)
func (_ Unimplemented) Oauth2Authorize(w http.ResponseWriter, r *http.Request, params Oauth2AuthorizeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OAuth2 callback endpoint
// (GET /auth/oauth2/callback)
func (_ Unimplemented) Oauth2Callback(w http.ResponseWriter, r *http.Request, params Oauth2CallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a server-managed session token
// (POST /auth/oauth2/revoke)
func (_ Unimplemented) Oauth2Revoke(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange authorization code for a server-managed session token
// (POST /auth/oauth2/token)
func (_ Unimplemented) Oauth2Token(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh a server-managed session token
// (POST /auth/refresh)
func (_ Unimplemented) AuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user information
// (GET /auth/userinfo)
func (_ Unimplemented) GetUserInfo(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostClaimAgent operation middleware
func (siw *ServerInterfaceWrapper) PostClaimAgent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{"agent:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostClaimAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterAgentSelf operation middleware
func (siw *ServerInterfaceWrapper) RegisterAgentSelf(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterAgentSelf(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentClaimStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentClaimStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId AgentId

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentClaimStatus(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentConfiguration operation middleware
func (siw *ServerInterfaceWrapper) GetAgentConfiguration(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId AgentId

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{"agent:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentConfiguration(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendAgentHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) SendAgentHeartbeat(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId AgentId

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendAgentHeartbeat(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitAgentResults operation middleware
func (siw *ServerInterfaceWrapper) SubmitAgentResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId AgentId

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentApiKeyScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitAgentResults(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{"agents:read"})

	ctx = context.WithValue(ctx, OAuth2ClientCredentialsScopes, []string{"agents:read"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAgentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Oauth2Authorize operation middleware
func (siw *ServerInterfaceWrapper) Oauth2Authorize(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params Oauth2AuthorizeParams

	// ------------- Required query parameter "provider" -------------

	if paramValue := r.URL.Query().Get("provider"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "provider"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "provider", r.URL.Query(), &params.Provider)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Required query parameter "scope" -------------

	if paramValue := r.URL.Query().Get("scope"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "scope"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Required query parameter "code_challenge" -------------

	if paramValue := r.URL.Query().Get("code_challenge"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code_challenge"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code_challenge", r.URL.Query(), &params.CodeChallenge)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge", Err: err})
		return
	}

	// ------------- Required query parameter "code_challenge_method" -------------

	if paramValue := r.URL.Query().Get("code_challenge_method"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code_challenge_method"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code_challenge_method", r.URL.Query(), &params.CodeChallengeMethod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge_method", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Oauth2Authorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Oauth2Callback operation middleware
func (siw *ServerInterfaceWrapper) Oauth2Callback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params Oauth2CallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Oauth2Callback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Oauth2Revoke operation middleware
func (siw *ServerInterfaceWrapper) Oauth2Revoke(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Oauth2Revoke(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Oauth2Token operation middleware
func (siw *ServerInterfaceWrapper) Oauth2Token(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Oauth2Token(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) AuthRefresh(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetUserInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{"openid", "profile", "email"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agent/claim", wrapper.PostClaimAgent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agent/register", wrapper.RegisterAgentSelf)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agent/{agentId}/claim-status", wrapper.GetAgentClaimStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agent/{agentId}/configuration", wrapper.GetAgentConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agent/{agentId}/heartbeat", wrapper.SendAgentHeartbeat)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agent/{agentId}/results", wrapper.SubmitAgentResults)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agents", wrapper.ListAgents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/oauth2/authorize", wrapper.Oauth2Authorize)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/oauth2/callback", wrapper.Oauth2Callback)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/oauth2/revoke", wrapper.Oauth2Revoke)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/oauth2/token", wrapper.Oauth2Token)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.AuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/userinfo", wrapper.GetUserInfo)
	})

	return r
}

type BadRequestJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type NotImplementedJSONResponse Error

type UnauthorizedJSONResponse Error

type UnprocessableEntityJSONResponse Error

type PostClaimAgentRequestObject struct {
	Body *PostClaimAgentJSONRequestBody
}

type PostClaimAgentResponseObject interface {
	VisitPostClaimAgentResponse(w http.ResponseWriter) error
}

type PostClaimAgent200JSONResponse ClaimAgentResponse

func (response PostClaimAgent200JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response PostClaimAgent400JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostClaimAgent401JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent403JSONResponse Error

func (response PostClaimAgent403JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent404JSONResponse Error

func (response PostClaimAgent404JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent409JSONResponse Error

func (response PostClaimAgent409JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostClaimAgent500JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAgentSelfRequestObject struct {
	Body *RegisterAgentSelfJSONRequestBody
}

type RegisterAgentSelfResponseObject interface {
	VisitRegisterAgentSelfResponse(w http.ResponseWriter) error
}

type RegisterAgentSelf200JSONResponse AgentRegistrationResponse

func (response RegisterAgentSelf200JSONResponse) VisitRegisterAgentSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAgentSelf201JSONResponse AgentRegistrationResponse

func (response RegisterAgentSelf201JSONResponse) VisitRegisterAgentSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAgentSelf400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterAgentSelf400JSONResponse) VisitRegisterAgentSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAgentSelf500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RegisterAgentSelf500JSONResponse) VisitRegisterAgentSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentClaimStatusRequestObject struct {
	AgentId AgentId `json:"agentId"`
}

type GetAgentClaimStatusResponseObject interface {
	VisitGetAgentClaimStatusResponse(w http.ResponseWriter) error
}

type GetAgentClaimStatus200JSONResponse struct {
	union json.RawMessage
}

func (response GetAgentClaimStatus200JSONResponse) VisitGetAgentClaimStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.union)
}

type GetAgentClaimStatus404JSONResponse Error

func (response GetAgentClaimStatus404JSONResponse) VisitGetAgentClaimStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentClaimStatus500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAgentClaimStatus500JSONResponse) VisitGetAgentClaimStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfigurationRequestObject struct {
	AgentId AgentId `json:"agentId"`
}

type GetAgentConfigurationResponseObject interface {
	VisitGetAgentConfigurationResponse(w http.ResponseWriter) error
}

type GetAgentConfiguration200JSONResponse AgentConfig

func (response GetAgentConfiguration200JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAgentConfiguration401JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAgentConfiguration404JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration501JSONResponse struct{ NotImplementedJSONResponse }

func (response GetAgentConfiguration501JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration503JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAgentConfiguration503JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type SendAgentHeartbeatRequestObject struct {
	AgentId AgentId `json:"agentId"`
	Body    *SendAgentHeartbeatJSONRequestBody
}

type SendAgentHeartbeatResponseObject interface {
	VisitSendAgentHeartbeatResponse(w http.ResponseWriter) error
}

type SendAgentHeartbeat204Response struct {
}

func (response SendAgentHeartbeat204Response) VisitSendAgentHeartbeatResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type SendAgentHeartbeat400JSONResponse struct{ BadRequestJSONResponse }

func (response SendAgentHeartbeat400JSONResponse) VisitSendAgentHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendAgentHeartbeat401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SendAgentHeartbeat401JSONResponse) VisitSendAgentHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendAgentHeartbeat503JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response SendAgentHeartbeat503JSONResponse) VisitSendAgentHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type SubmitAgentResultsRequestObject struct {
	AgentId AgentId `json:"agentId"`
	Body    *SubmitAgentResultsJSONRequestBody
}

type SubmitAgentResultsResponseObject interface {
	VisitSubmitAgentResultsResponse(w http.ResponseWriter) error
}

type SubmitAgentResults202JSONResponse ResultsBatchAcknowledgment

func (response SubmitAgentResults202JSONResponse) VisitSubmitAgentResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type SubmitAgentResults400JSONResponse struct{ BadRequestJSONResponse }

func (response SubmitAgentResults400JSONResponse) VisitSubmitAgentResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SubmitAgentResults401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SubmitAgentResults401JSONResponse) VisitSubmitAgentResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SubmitAgentResults422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response SubmitAgentResults422JSONResponse) VisitSubmitAgentResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type SubmitAgentResults503JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response SubmitAgentResults503JSONResponse) VisitSubmitAgentResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type ListAgentsRequestObject struct {
	Params ListAgentsParams
}

type ListAgentsResponseObject interface {
	VisitListAgentsResponse(w http.ResponseWriter) error
}

type ListAgents200JSONResponse AgentListResponse

func (response ListAgents200JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListAgents401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListAgents401JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListAgents500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListAgents500JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Logout302ResponseHeaders struct {
	Location string
}

type Logout302Response struct {
	Headers Logout302ResponseHeaders
}

func (response Logout302Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type Logout400JSONResponse struct{ BadRequestJSONResponse }

func (response Logout400JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2AuthorizeRequestObject struct {
	Params Oauth2AuthorizeParams
}

type Oauth2AuthorizeResponseObject interface {
	VisitOauth2AuthorizeResponse(w http.ResponseWriter) error
}

type Oauth2Authorize302ResponseHeaders struct {
	Location string
}

type Oauth2Authorize302Response struct {
	Headers Oauth2Authorize302ResponseHeaders
}

func (response Oauth2Authorize302Response) VisitOauth2AuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type Oauth2Authorize400JSONResponse struct{ BadRequestJSONResponse }

func (response Oauth2Authorize400JSONResponse) VisitOauth2AuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2CallbackRequestObject struct {
	Params Oauth2CallbackParams
}

type Oauth2CallbackResponseObject interface {
	VisitOauth2CallbackResponse(w http.ResponseWriter) error
}

type Oauth2Callback302ResponseHeaders struct {
	Location string
}

type Oauth2Callback302Response struct {
	Headers Oauth2Callback302ResponseHeaders
}

func (response Oauth2Callback302Response) VisitOauth2CallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type Oauth2RevokeRequestObject struct {
	Body *Oauth2RevokeJSONRequestBody
}

type Oauth2RevokeResponseObject interface {
	VisitOauth2RevokeResponse(w http.ResponseWriter) error
}

type Oauth2Revoke200JSONResponse struct {
	// Warning Present if IdP revocation was skipped (provider limitation)
	Warning *string `json:"warning,omitempty"`
}

func (response Oauth2Revoke200JSONResponse) VisitOauth2RevokeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2Revoke400JSONResponse struct{ BadRequestJSONResponse }

func (response Oauth2Revoke400JSONResponse) VisitOauth2RevokeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2Revoke401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Oauth2Revoke401JSONResponse) VisitOauth2RevokeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2TokenRequestObject struct {
	Body *Oauth2TokenFormdataRequestBody
}

type Oauth2TokenResponseObject interface {
	VisitOauth2TokenResponse(w http.ResponseWriter) error
}

type Oauth2Token200JSONResponse TokenResponse

func (response Oauth2Token200JSONResponse) VisitOauth2TokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2Token400JSONResponse struct{ BadRequestJSONResponse }

func (response Oauth2Token400JSONResponse) VisitOauth2TokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2Token401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Oauth2Token401JSONResponse) VisitOauth2TokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AuthRefreshRequestObject struct {
}

type AuthRefreshResponseObject interface {
	VisitAuthRefreshResponse(w http.ResponseWriter) error
}

type AuthRefresh200JSONResponse TokenResponse

func (response AuthRefresh200JSONResponse) VisitAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthRefresh401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AuthRefresh401JSONResponse) VisitAuthRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfoRequestObject struct {
}

type GetUserInfoResponseObject interface {
	VisitGetUserInfoResponse(w http.ResponseWriter) error
}

type GetUserInfo200JSONResponse UserInfo

func (response GetUserInfo200JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfo400JSONResponse struct{ BadRequestJSONResponse }

func (response GetUserInfo400JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserInfo401JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Claim an agent (Web UI)
	// (POST /agent/claim)
	PostClaimAgent(ctx context.Context, request PostClaimAgentRequestObject) (PostClaimAgentResponseObject, error)
	// Agent self-registration (unclaimed)
	// (POST /agent/register)
	RegisterAgentSelf(ctx context.Context, request RegisterAgentSelfRequestObject) (RegisterAgentSelfResponseObject, error)
	// Check agent claim status (polling endpoint)
	// (GET /agent/{agentId}/claim-status)
	GetAgentClaimStatus(ctx context.Context, request GetAgentClaimStatusRequestObject) (GetAgentClaimStatusResponseObject, error)
	// Get agent configuration
	// (GET /agent/{agentId}/configuration)
	GetAgentConfiguration(ctx context.Context, request GetAgentConfigurationRequestObject) (GetAgentConfigurationResponseObject, error)
	// Send agent heartbeat
	// (POST /agent/{agentId}/heartbeat)
	SendAgentHeartbeat(ctx context.Context, request SendAgentHeartbeatRequestObject) (SendAgentHeartbeatResponseObject, error)
	// Submit batch monitoring results
	// (POST /agent/{agentId}/results)
	SubmitAgentResults(ctx context.Context, request SubmitAgentResultsRequestObject) (SubmitAgentResultsResponseObject, error)
	// List agents
	// (GET /agents)
	ListAgents(ctx context.Context, request ListAgentsRequestObject) (ListAgentsResponseObject, error)
	// User logout
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// OAuth2 authorization endpoint
	// (GET /auth/oauth2/authorize)
	Oauth2Authorize(ctx context.Context, request Oauth2AuthorizeRequestObject) (Oauth2AuthorizeResponseObject, error)
	// OAuth2 callback endpoint
	// (GET /auth/oauth2/callback)
	Oauth2Callback(ctx context.Context, request Oauth2CallbackRequestObject) (Oauth2CallbackResponseObject, error)
	// Revoke a server-managed session token
	// (POST /auth/oauth2/revoke)
	Oauth2Revoke(ctx context.Context, request Oauth2RevokeRequestObject) (Oauth2RevokeResponseObject, error)
	// Exchange authorization code for a server-managed session token
	// (POST /auth/oauth2/token)
	Oauth2Token(ctx context.Context, request Oauth2TokenRequestObject) (Oauth2TokenResponseObject, error)
	// Refresh a server-managed session token
	// (POST /auth/refresh)
	AuthRefresh(ctx context.Context, request AuthRefreshRequestObject) (AuthRefreshResponseObject, error)
	// Get current user information
	// (GET /auth/userinfo)
	GetUserInfo(ctx context.Context, request GetUserInfoRequestObject) (GetUserInfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostClaimAgent operation middleware
func (sh *strictHandler) PostClaimAgent(w http.ResponseWriter, r *http.Request) {
	var request PostClaimAgentRequestObject

	var body PostClaimAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostClaimAgent(ctx, request.(PostClaimAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostClaimAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostClaimAgentResponseObject); ok {
		if err := validResponse.VisitPostClaimAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterAgentSelf operation middleware
func (sh *strictHandler) RegisterAgentSelf(w http.ResponseWriter, r *http.Request) {
	var request RegisterAgentSelfRequestObject

	var body RegisterAgentSelfJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterAgentSelf(ctx, request.(RegisterAgentSelfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterAgentSelf")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterAgentSelfResponseObject); ok {
		if err := validResponse.VisitRegisterAgentSelfResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgentClaimStatus operation middleware
func (sh *strictHandler) GetAgentClaimStatus(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	var request GetAgentClaimStatusRequestObject

	request.AgentId = agentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentClaimStatus(ctx, request.(GetAgentClaimStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentClaimStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentClaimStatusResponseObject); ok {
		if err := validResponse.VisitGetAgentClaimStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgentConfiguration operation middleware
func (sh *strictHandler) GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	var request GetAgentConfigurationRequestObject

	request.AgentId = agentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentConfiguration(ctx, request.(GetAgentConfigurationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentConfiguration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentConfigurationResponseObject); ok {
		if err := validResponse.VisitGetAgentConfigurationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendAgentHeartbeat operation middleware
func (sh *strictHandler) SendAgentHeartbeat(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	var request SendAgentHeartbeatRequestObject

	request.AgentId = agentId

	var body SendAgentHeartbeatJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SendAgentHeartbeat(ctx, request.(SendAgentHeartbeatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendAgentHeartbeat")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SendAgentHeartbeatResponseObject); ok {
		if err := validResponse.VisitSendAgentHeartbeatResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitAgentResults operation middleware
func (sh *strictHandler) SubmitAgentResults(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	var request SubmitAgentResultsRequestObject

	request.AgentId = agentId

	var body SubmitAgentResultsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitAgentResults(ctx, request.(SubmitAgentResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitAgentResults")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitAgentResultsResponseObject); ok {
		if err := validResponse.VisitSubmitAgentResultsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAgents operation middleware
func (sh *strictHandler) ListAgents(w http.ResponseWriter, r *http.Request, params ListAgentsParams) {
	var request ListAgentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAgents(ctx, request.(ListAgentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAgents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAgentsResponseObject); ok {
		if err := validResponse.VisitListAgentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Oauth2Authorize operation middleware
func (sh *strictHandler) Oauth2Authorize(w http.ResponseWriter, r *http.Request, params Oauth2AuthorizeParams) {
	var request Oauth2AuthorizeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Oauth2Authorize(ctx, request.(Oauth2AuthorizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Oauth2Authorize")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(Oauth2AuthorizeResponseObject); ok {
		if err := validResponse.VisitOauth2AuthorizeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Oauth2Callback operation middleware
func (sh *strictHandler) Oauth2Callback(w http.ResponseWriter, r *http.Request, params Oauth2CallbackParams) {
	var request Oauth2CallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Oauth2Callback(ctx, request.(Oauth2CallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Oauth2Callback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(Oauth2CallbackResponseObject); ok {
		if err := validResponse.VisitOauth2CallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Oauth2Revoke operation middleware
func (sh *strictHandler) Oauth2Revoke(w http.ResponseWriter, r *http.Request) {
	var request Oauth2RevokeRequestObject

	var body Oauth2RevokeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Oauth2Revoke(ctx, request.(Oauth2RevokeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Oauth2Revoke")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(Oauth2RevokeResponseObject); ok {
		if err := validResponse.VisitOauth2RevokeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Oauth2Token operation middleware
func (sh *strictHandler) Oauth2Token(w http.ResponseWriter, r *http.Request) {
	var request Oauth2TokenRequestObject

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body Oauth2TokenFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Oauth2Token(ctx, request.(Oauth2TokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Oauth2Token")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(Oauth2TokenResponseObject); ok {
		if err := validResponse.VisitOauth2TokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthRefresh operation middleware
func (sh *strictHandler) AuthRefresh(w http.ResponseWriter, r *http.Request) {
	var request AuthRefreshRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthRefresh(ctx, request.(AuthRefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthRefresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthRefreshResponseObject); ok {
		if err := validResponse.VisitAuthRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserInfo operation middleware
func (sh *strictHandler) GetUserInfo(w http.ResponseWriter, r *http.Request) {
	var request GetUserInfoRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserInfo(ctx, request.(GetUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserInfoResponseObject); ok {
		if err := validResponse.VisitGetUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
