// Package api_v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api_v1

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AgentApiKeyScopes             = "AgentApiKey.Scopes"
	OAuth2AuthorizationCodeScopes = "OAuth2AuthorizationCode.Scopes"
)

// Defines values for ClaimResponseStatus.
const (
	ClaimResponseStatusClaimed ClaimResponseStatus = "claimed"
)

// Defines values for ClaimStatusClaimedEnum.
const (
	ClaimStatusClaimedEnumClaimed ClaimStatusClaimedEnum = "claimed"
)

// Defines values for ClaimStatusPendingEnum.
const (
	ClaimStatusPendingEnumPendingClaim ClaimStatusPendingEnum = "pending_claim"
)

// Defines values for RegistrationStatus.
const (
	RegistrationStatusPendingClaim RegistrationStatus = "pending_claim"
)

// Defines values for Oauth2AuthorizeParamsCodeChallengeMethod.
const (
	S256 Oauth2AuthorizeParamsCodeChallengeMethod = "S256"
)

// Defines values for Oauth2RevokeFormdataBodyTokenTypeHint.
const (
	Oauth2RevokeFormdataBodyTokenTypeHintAccessToken  Oauth2RevokeFormdataBodyTokenTypeHint = "access_token"
	Oauth2RevokeFormdataBodyTokenTypeHintRefreshToken Oauth2RevokeFormdataBodyTokenTypeHint = "refresh_token"
)

// Defines values for Oauth2TokenFormdataBodyGrantType.
const (
	Oauth2TokenFormdataBodyGrantTypeAuthorizationCode Oauth2TokenFormdataBodyGrantType = "authorization_code"
	Oauth2TokenFormdataBodyGrantTypeRefreshToken      Oauth2TokenFormdataBodyGrantType = "refresh_token"
)

// AgentConfig defines model for AgentConfig.
type AgentConfig struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agent_id"`

	// AgentName Human-readable agent name
	AgentName string `json:"agent_name"`

	// Endpoints Endpoints to monitor
	Endpoints  []Endpoint       `json:"endpoints"`
	Monitoring MonitoringConfig `json:"monitoring"`
	Server     ServerConfig     `json:"server"`
	Storage    StorageConfig    `json:"storage"`

	// Tags Tags for this agent (used for mesh organization)
	Tags *[]string `json:"tags,omitempty"`

	// Version Configuration version (used for syncing with server)
	Version int32 `json:"version"`
}

// AgentRegistrationResponse defines model for AgentRegistrationResponse.
type AgentRegistrationResponse struct {
	// ClaimUrl URL for user to claim the agent (web UI)
	ClaimUrl string `json:"claimUrl"`

	// ExpiresAt When the claim token expires (RFC3339)
	ExpiresAt time.Time `json:"expiresAt"`

	// PollUrl URL for agent to poll for claim status
	PollUrl string `json:"pollUrl"`

	// Status Status of agent registration
	Status RegistrationStatus `json:"status"`
}

// AgentSelfRegistration defines model for AgentSelfRegistration.
type AgentSelfRegistration struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agentId"`

	// AgentVersion Version of the agent software
	AgentVersion string `json:"agentVersion"`

	// ClaimTokenHash SHA-256 hash of the claim token (plain token shown in agent logs for user)
	ClaimTokenHash string `json:"claimTokenHash"`

	// Hostname System hostname of the machine running the agent
	Hostname string `json:"hostname"`
}

// ClaimAgentRequest defines model for ClaimAgentRequest.
type ClaimAgentRequest struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agentId"`

	// ClaimToken Claim token from agent logs
	ClaimToken string `json:"claimToken"`

	// Name Human-readable name for the agent (defaults to hostname if not provided)
	Name *string `json:"name,omitempty"`

	// SectionId UUID version 7 as per RFC 4122
	SectionId UUIDv7 `json:"sectionId"`
}

// ClaimAgentResponse defines model for ClaimAgentResponse.
type ClaimAgentResponse struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agentId"`

	// Message Human-readable message
	Message string `json:"message"`

	// Status Status in claim response
	Status ClaimResponseStatus `json:"status"`
}

// ClaimResponseStatus Status in claim response
type ClaimResponseStatus string

// ClaimStatusClaimed defines model for ClaimStatusClaimed.
type ClaimStatusClaimed struct {
	// ApiKey API key for authenticated requests (one-time delivery)
	ApiKey string `json:"apiKey"`

	// ConfigUrl URL to fetch agent configuration
	ConfigUrl string `json:"configUrl"`

	// Status Claimed status
	Status ClaimStatusClaimedEnum `json:"status"`
}

// ClaimStatusClaimedEnum Claimed status
type ClaimStatusClaimedEnum string

// ClaimStatusPending defines model for ClaimStatusPending.
type ClaimStatusPending struct {
	// ExpiresAt When the claim token expires (RFC3339)
	ExpiresAt time.Time `json:"expiresAt"`

	// PollIn Seconds until next poll (server-controlled backoff)
	PollIn int32 `json:"pollIn"`

	// Status Pending claim status
	Status ClaimStatusPendingEnum `json:"status"`
}

// ClaimStatusPendingEnum Pending claim status
type ClaimStatusPendingEnum string

// Endpoint defines model for Endpoint.
type Endpoint struct {
	// Address IP address, hostname, or URL
	Address string `json:"address"`
	Enabled bool   `json:"enabled"`

	// Id UUID version 7 as per RFC 4122
	Id   UUIDv7 `json:"id"`
	Port *int   `json:"port,omitempty"`

	// Tags Tags associated with the target
	Tags *[]string `json:"tags,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Details *[]struct {
		Field *string `json:"field,omitempty"`
		Issue *string `json:"issue,omitempty"`
	} `json:"details,omitempty"`

	// DocumentationUrl Link to relevant documentation
	DocumentationUrl *string             `json:"documentation_url,omitempty"`
	Error            string              `json:"error"`
	Message          string              `json:"message"`
	RequestId        *openapi_types.UUID `json:"request_id,omitempty"`
}

// MonitoringConfig defines model for MonitoringConfig.
type MonitoringConfig struct {
	// IntervalSecs Interval between checks in seconds
	IntervalSecs int64 `json:"interval_secs"`

	// MaxConcurrent Maximum number of concurrent checks
	MaxConcurrent int `json:"max_concurrent"`

	// PingCount Number of pings to send per check
	PingCount int32 `json:"ping_count"`

	// TimeoutSecs Timeout for each check in seconds
	TimeoutSecs int64 `json:"timeout_secs"`

	// TracerouteMaxHops Maximum TTL for traceroute
	TracerouteMaxHops int32 `json:"traceroute_max_hops"`

	// TracerouteOnFailure Enable traceroute on failed pings
	TracerouteOnFailure bool `json:"traceroute_on_failure"`
}

// RegistrationStatus Status of agent registration
type RegistrationStatus string

// ServerConfig defines model for ServerConfig.
type ServerConfig struct {
	// ApiKey API key for authentication
	ApiKey *string `json:"api_key"`

	// HeartbeatIntervalSecs Heartbeat interval in seconds
	HeartbeatIntervalSecs int64 `json:"heartbeat_interval_secs"`

	// ReportIntervalSecs Report interval in seconds
	ReportIntervalSecs int64 `json:"report_interval_secs"`

	// RetryAttempts Retry attempts on failure
	RetryAttempts int32 `json:"retry_attempts"`

	// TimeoutSecs Connection timeout in seconds
	TimeoutSecs int64 `json:"timeout_secs"`

	// Url Server URL
	Url *string `json:"url"`

	// VerifyTls Enable TLS verification
	VerifyTls bool `json:"verify_tls"`
}

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// CacheDir Directory for storing cached data
	CacheDir string `json:"cache_dir"`

	// MaxCacheAgeSecs Maximum age of cached results in seconds (e.g., 86400 = 24 hours)
	MaxCacheAgeSecs int64 `json:"max_cache_age_secs"`

	// MaxCachedResults Maximum number of results to cache
	MaxCachedResults int `json:"max_cached_results"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken JWT access token
	AccessToken string `json:"access_token"`

	// ExpiresIn Token lifetime in seconds
	ExpiresIn int `json:"expires_in"`

	// IdToken OpenID Connect ID token (if openid scope requested)
	IdToken *string `json:"id_token,omitempty"`

	// RefreshToken Refresh token (only for authorization_code grant)
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Scope Space-separated list of granted scopes
	Scope     *string `json:"scope,omitempty"`
	TokenType string  `json:"token_type"`
}

// UUIDv7 UUID version 7 as per RFC 4122
type UUIDv7 = uuid.UUID

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email          *openapi_types.Email `json:"email,omitempty"`
	EmailVerified  *bool                `json:"email_verified,omitempty"`
	FamilyName     *string              `json:"family_name,omitempty"`
	GivenName      *string              `json:"given_name,omitempty"`
	Name           *string              `json:"name,omitempty"`
	OrganizationId *openapi_types.UUID  `json:"organization_id,omitempty"`
	Permissions    *[]string            `json:"permissions,omitempty"`
	Picture        *string              `json:"picture,omitempty"`
	Roles          *[]string            `json:"roles,omitempty"`

	// Sub Subject identifier (user ID)
	Sub string `json:"sub"`
}

// AgentId UUID version 7 as per RFC 4122
type AgentId = UUIDv7

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// NotImplemented defines model for NotImplemented.
type NotImplemented = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// LogoutJSONBody defines parameters for Logout.
type LogoutJSONBody struct {
	// PostLogoutRedirectUri Optional URI to redirect to after IDP logout completes.
	// Forwarded to the IDP end-session endpoint as post_logout_redirect_uri.
	PostLogoutRedirectUri *string `json:"post_logout_redirect_uri,omitempty"`

	// Provider Identity provider name. Must match a provider configured on the server.
	// Built-in values: okta, auth0, azure, google, github.
	Provider string `json:"provider"`
}

// Oauth2AuthorizeParams defines parameters for Oauth2Authorize.
type Oauth2AuthorizeParams struct {
	// Provider Identity provider name. Must match a provider configured on the server.
	// Built-in values: okta, auth0, azure, google, github.
	Provider string `form:"provider" json:"provider"`

	// Scope Space-separated list of requested scopes
	Scope string `form:"scope" json:"scope"`

	// State CSRF protection token generated by the client
	State string `form:"state" json:"state"`

	// CodeChallenge PKCE code challenge (BASE64URL(SHA256(code_verifier)))
	CodeChallenge string `form:"code_challenge" json:"code_challenge"`

	// CodeChallengeMethod PKCE code challenge method — must be S256
	CodeChallengeMethod Oauth2AuthorizeParamsCodeChallengeMethod `form:"code_challenge_method" json:"code_challenge_method"`
}

// Oauth2AuthorizeParamsCodeChallengeMethod defines parameters for Oauth2Authorize.
type Oauth2AuthorizeParamsCodeChallengeMethod string

// Oauth2CallbackParams defines parameters for Oauth2Callback.
type Oauth2CallbackParams struct {
	// Code Authorization code issued by the identity provider
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State CSRF protection token (must match the original authorize request)
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Error code if authorization failed at the IDP
	Error *string `form:"error,omitempty" json:"error,omitempty"`

	// ErrorDescription Human-readable error description from the IDP
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
}

// Oauth2RevokeFormdataBody defines parameters for Oauth2Revoke.
type Oauth2RevokeFormdataBody struct {
	// Provider Identity provider name. Must match a provider configured on the server.
	// Built-in values: okta, auth0, azure, google, github.
	Provider string `form:"provider" json:"provider"`

	// Token Token to revoke
	Token string `form:"token" json:"token"`

	// TokenTypeHint Optional hint about the token type
	TokenTypeHint *Oauth2RevokeFormdataBodyTokenTypeHint `form:"token_type_hint,omitempty" json:"token_type_hint,omitempty"`
}

// Oauth2RevokeFormdataBodyTokenTypeHint defines parameters for Oauth2Revoke.
type Oauth2RevokeFormdataBodyTokenTypeHint string

// Oauth2TokenFormdataBody defines parameters for Oauth2Token.
type Oauth2TokenFormdataBody struct {
	// Code Authorization code (required for authorization_code grant)
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// CodeVerifier PKCE code verifier (required for authorization_code grant)
	CodeVerifier *string `form:"code_verifier,omitempty" json:"code_verifier,omitempty"`

	// GrantType OAuth2 grant type
	GrantType Oauth2TokenFormdataBodyGrantType `form:"grant_type" json:"grant_type"`

	// Provider Identity provider name. Must match a provider configured on the server.
	// Built-in values: okta, auth0, azure, google, github.
	Provider string `form:"provider" json:"provider"`

	// RedirectUri Must exactly match the redirect_uri used in the authorization request (required for authorization_code grant)
	RedirectUri *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`

	// RefreshToken Refresh token (required for refresh_token grant)
	RefreshToken *string `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`

	// Scope Optional scope restriction (refresh_token grant only)
	Scope *string `form:"scope,omitempty" json:"scope,omitempty"`
}

// Oauth2TokenFormdataBodyGrantType defines parameters for Oauth2Token.
type Oauth2TokenFormdataBodyGrantType string

// GetUserInfoParams defines parameters for GetUserInfo.
type GetUserInfoParams struct {
	// Provider Identity provider name. Must match a provider configured on the server.
	// Built-in values: okta, auth0, azure, google, github.
	Provider string `form:"provider" json:"provider"`
}

// PostClaimAgentJSONRequestBody defines body for PostClaimAgent for application/json ContentType.
type PostClaimAgentJSONRequestBody = ClaimAgentRequest

// RegisterAgentSelfJSONRequestBody defines body for RegisterAgentSelf for application/json ContentType.
type RegisterAgentSelfJSONRequestBody = AgentSelfRegistration

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody LogoutJSONBody

// Oauth2RevokeFormdataRequestBody defines body for Oauth2Revoke for application/x-www-form-urlencoded ContentType.
type Oauth2RevokeFormdataRequestBody Oauth2RevokeFormdataBody

// Oauth2TokenFormdataRequestBody defines body for Oauth2Token for application/x-www-form-urlencoded ContentType.
type Oauth2TokenFormdataRequestBody Oauth2TokenFormdataBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Claim an agent (Web UI)
	// (POST /agent/claim)
	PostClaimAgent(w http.ResponseWriter, r *http.Request)
	// Agent self-registration (unclaimed)
	// (POST /agent/register)
	RegisterAgentSelf(w http.ResponseWriter, r *http.Request)
	// Check agent claim status (polling endpoint)
	// (GET /agent/{agentId}/claim-status)
	GetAgentClaimStatus(w http.ResponseWriter, r *http.Request, agentId AgentId)
	// Get agent configuration
	// (GET /agent/{agentId}/configuration)
	GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId)
	// User logout
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// OAuth2 authorization endpoint
	// (GET /auth/oauth2/authorize)
	Oauth2Authorize(w http.ResponseWriter, r *http.Request, params Oauth2AuthorizeParams)
	// OAuth2 callback endpoint
	// (GET /auth/oauth2/callback)
	Oauth2Callback(w http.ResponseWriter, r *http.Request, params Oauth2CallbackParams)
	// Revoke access or refresh token
	// (POST /auth/oauth2/revoke)
	Oauth2Revoke(w http.ResponseWriter, r *http.Request)
	// Exchange authorization code or refresh token for tokens
	// (POST /auth/oauth2/token)
	Oauth2Token(w http.ResponseWriter, r *http.Request)
	// Get current user information
	// (GET /auth/userinfo)
	GetUserInfo(w http.ResponseWriter, r *http.Request, params GetUserInfoParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Claim an agent (Web UI)
// (POST /agent/claim)
func (_ Unimplemented) PostClaimAgent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Agent self-registration (unclaimed)
// (POST /agent/register)
func (_ Unimplemented) RegisterAgentSelf(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check agent claim status (polling endpoint)
// (GET /agent/{agentId}/claim-status)
func (_ Unimplemented) GetAgentClaimStatus(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get agent configuration
// (GET /agent/{agentId}/configuration)
func (_ Unimplemented) GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User logout
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OAuth2 authorization endpoint
// (GET /auth/oauth2/authorize)
func (_ Unimplemented) Oauth2Authorize(w http.ResponseWriter, r *http.Request, params Oauth2AuthorizeParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// OAuth2 callback endpoint
// (GET /auth/oauth2/callback)
func (_ Unimplemented) Oauth2Callback(w http.ResponseWriter, r *http.Request, params Oauth2CallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke access or refresh token
// (POST /auth/oauth2/revoke)
func (_ Unimplemented) Oauth2Revoke(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange authorization code or refresh token for tokens
// (POST /auth/oauth2/token)
func (_ Unimplemented) Oauth2Token(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user information
// (GET /auth/userinfo)
func (_ Unimplemented) GetUserInfo(w http.ResponseWriter, r *http.Request, params GetUserInfoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostClaimAgent operation middleware
func (siw *ServerInterfaceWrapper) PostClaimAgent(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{"agent:write"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostClaimAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterAgentSelf operation middleware
func (siw *ServerInterfaceWrapper) RegisterAgentSelf(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterAgentSelf(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentClaimStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentClaimStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId AgentId

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentClaimStatus(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentConfiguration operation middleware
func (siw *ServerInterfaceWrapper) GetAgentConfiguration(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId AgentId

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{"agent:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentConfiguration(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Oauth2Authorize operation middleware
func (siw *ServerInterfaceWrapper) Oauth2Authorize(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params Oauth2AuthorizeParams

	// ------------- Required query parameter "provider" -------------

	if paramValue := r.URL.Query().Get("provider"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "provider"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "provider", r.URL.Query(), &params.Provider)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Required query parameter "scope" -------------

	if paramValue := r.URL.Query().Get("scope"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "scope"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Required query parameter "code_challenge" -------------

	if paramValue := r.URL.Query().Get("code_challenge"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code_challenge"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code_challenge", r.URL.Query(), &params.CodeChallenge)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge", Err: err})
		return
	}

	// ------------- Required query parameter "code_challenge_method" -------------

	if paramValue := r.URL.Query().Get("code_challenge_method"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code_challenge_method"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code_challenge_method", r.URL.Query(), &params.CodeChallengeMethod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge_method", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Oauth2Authorize(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Oauth2Callback operation middleware
func (siw *ServerInterfaceWrapper) Oauth2Callback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params Oauth2CallbackParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, false, "code", r.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameter("form", true, false, "error", r.URL.Query(), &params.Error)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		return
	}

	// ------------- Optional query parameter "error_description" -------------

	err = runtime.BindQueryParameter("form", true, false, "error_description", r.URL.Query(), &params.ErrorDescription)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_description", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Oauth2Callback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Oauth2Revoke operation middleware
func (siw *ServerInterfaceWrapper) Oauth2Revoke(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Oauth2Revoke(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Oauth2Token operation middleware
func (siw *ServerInterfaceWrapper) Oauth2Token(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Oauth2Token(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetUserInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{"openid", "profile", "email"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserInfoParams

	// ------------- Required query parameter "provider" -------------

	if paramValue := r.URL.Query().Get("provider"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "provider"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "provider", r.URL.Query(), &params.Provider)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInfo(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agent/claim", wrapper.PostClaimAgent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/agent/register", wrapper.RegisterAgentSelf)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agent/{agentId}/claim-status", wrapper.GetAgentClaimStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agent/{agentId}/configuration", wrapper.GetAgentConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/oauth2/authorize", wrapper.Oauth2Authorize)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/oauth2/callback", wrapper.Oauth2Callback)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/oauth2/revoke", wrapper.Oauth2Revoke)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/oauth2/token", wrapper.Oauth2Token)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/userinfo", wrapper.GetUserInfo)
	})

	return r
}

type BadRequestJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type NotImplementedJSONResponse Error

type UnauthorizedJSONResponse Error

type PostClaimAgentRequestObject struct {
	Body *PostClaimAgentJSONRequestBody
}

type PostClaimAgentResponseObject interface {
	VisitPostClaimAgentResponse(w http.ResponseWriter) error
}

type PostClaimAgent200JSONResponse ClaimAgentResponse

func (response PostClaimAgent200JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent400JSONResponse struct{ BadRequestJSONResponse }

func (response PostClaimAgent400JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PostClaimAgent401JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent403JSONResponse Error

func (response PostClaimAgent403JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent404JSONResponse Error

func (response PostClaimAgent404JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent409JSONResponse Error

func (response PostClaimAgent409JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PostClaimAgent500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PostClaimAgent500JSONResponse) VisitPostClaimAgentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAgentSelfRequestObject struct {
	Body *RegisterAgentSelfJSONRequestBody
}

type RegisterAgentSelfResponseObject interface {
	VisitRegisterAgentSelfResponse(w http.ResponseWriter) error
}

type RegisterAgentSelf200JSONResponse AgentRegistrationResponse

func (response RegisterAgentSelf200JSONResponse) VisitRegisterAgentSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAgentSelf201JSONResponse AgentRegistrationResponse

func (response RegisterAgentSelf201JSONResponse) VisitRegisterAgentSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAgentSelf400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterAgentSelf400JSONResponse) VisitRegisterAgentSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterAgentSelf500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RegisterAgentSelf500JSONResponse) VisitRegisterAgentSelfResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentClaimStatusRequestObject struct {
	AgentId AgentId `json:"agentId"`
}

type GetAgentClaimStatusResponseObject interface {
	VisitGetAgentClaimStatusResponse(w http.ResponseWriter) error
}

type GetAgentClaimStatus200JSONResponse struct {
	union json.RawMessage
}

func (response GetAgentClaimStatus200JSONResponse) VisitGetAgentClaimStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.union)
}

type GetAgentClaimStatus404JSONResponse Error

func (response GetAgentClaimStatus404JSONResponse) VisitGetAgentClaimStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentClaimStatus500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAgentClaimStatus500JSONResponse) VisitGetAgentClaimStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfigurationRequestObject struct {
	AgentId AgentId `json:"agentId"`
}

type GetAgentConfigurationResponseObject interface {
	VisitGetAgentConfigurationResponse(w http.ResponseWriter) error
}

type GetAgentConfiguration200JSONResponse AgentConfig

func (response GetAgentConfiguration200JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAgentConfiguration401JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAgentConfiguration404JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration501JSONResponse struct{ NotImplementedJSONResponse }

func (response GetAgentConfiguration501JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration503JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAgentConfiguration503JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Logout302ResponseHeaders struct {
	Location string
}

type Logout302Response struct {
	Headers Logout302ResponseHeaders
}

func (response Logout302Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type Logout400JSONResponse struct{ BadRequestJSONResponse }

func (response Logout400JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2AuthorizeRequestObject struct {
	Params Oauth2AuthorizeParams
}

type Oauth2AuthorizeResponseObject interface {
	VisitOauth2AuthorizeResponse(w http.ResponseWriter) error
}

type Oauth2Authorize302ResponseHeaders struct {
	Location string
}

type Oauth2Authorize302Response struct {
	Headers Oauth2Authorize302ResponseHeaders
}

func (response Oauth2Authorize302Response) VisitOauth2AuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type Oauth2Authorize400JSONResponse struct{ BadRequestJSONResponse }

func (response Oauth2Authorize400JSONResponse) VisitOauth2AuthorizeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2CallbackRequestObject struct {
	Params Oauth2CallbackParams
}

type Oauth2CallbackResponseObject interface {
	VisitOauth2CallbackResponse(w http.ResponseWriter) error
}

type Oauth2Callback302ResponseHeaders struct {
	Location string
}

type Oauth2Callback302Response struct {
	Headers Oauth2Callback302ResponseHeaders
}

func (response Oauth2Callback302Response) VisitOauth2CallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type Oauth2RevokeRequestObject struct {
	Body *Oauth2RevokeFormdataRequestBody
}

type Oauth2RevokeResponseObject interface {
	VisitOauth2RevokeResponse(w http.ResponseWriter) error
}

type Oauth2Revoke200JSONResponse struct {
	// Warning Present if revocation was not performed (provider limitation)
	Warning *string `json:"warning,omitempty"`
}

func (response Oauth2Revoke200JSONResponse) VisitOauth2RevokeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2Revoke400JSONResponse struct{ BadRequestJSONResponse }

func (response Oauth2Revoke400JSONResponse) VisitOauth2RevokeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2Revoke401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Oauth2Revoke401JSONResponse) VisitOauth2RevokeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2TokenRequestObject struct {
	Body *Oauth2TokenFormdataRequestBody
}

type Oauth2TokenResponseObject interface {
	VisitOauth2TokenResponse(w http.ResponseWriter) error
}

type Oauth2Token200JSONResponse TokenResponse

func (response Oauth2Token200JSONResponse) VisitOauth2TokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2Token400JSONResponse struct{ BadRequestJSONResponse }

func (response Oauth2Token400JSONResponse) VisitOauth2TokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Oauth2Token401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Oauth2Token401JSONResponse) VisitOauth2TokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfoRequestObject struct {
	Params GetUserInfoParams
}

type GetUserInfoResponseObject interface {
	VisitGetUserInfoResponse(w http.ResponseWriter) error
}

type GetUserInfo200JSONResponse UserInfo

func (response GetUserInfo200JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfo400JSONResponse struct{ BadRequestJSONResponse }

func (response GetUserInfo400JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetUserInfo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserInfo401JSONResponse) VisitGetUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Claim an agent (Web UI)
	// (POST /agent/claim)
	PostClaimAgent(ctx context.Context, request PostClaimAgentRequestObject) (PostClaimAgentResponseObject, error)
	// Agent self-registration (unclaimed)
	// (POST /agent/register)
	RegisterAgentSelf(ctx context.Context, request RegisterAgentSelfRequestObject) (RegisterAgentSelfResponseObject, error)
	// Check agent claim status (polling endpoint)
	// (GET /agent/{agentId}/claim-status)
	GetAgentClaimStatus(ctx context.Context, request GetAgentClaimStatusRequestObject) (GetAgentClaimStatusResponseObject, error)
	// Get agent configuration
	// (GET /agent/{agentId}/configuration)
	GetAgentConfiguration(ctx context.Context, request GetAgentConfigurationRequestObject) (GetAgentConfigurationResponseObject, error)
	// User logout
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// OAuth2 authorization endpoint
	// (GET /auth/oauth2/authorize)
	Oauth2Authorize(ctx context.Context, request Oauth2AuthorizeRequestObject) (Oauth2AuthorizeResponseObject, error)
	// OAuth2 callback endpoint
	// (GET /auth/oauth2/callback)
	Oauth2Callback(ctx context.Context, request Oauth2CallbackRequestObject) (Oauth2CallbackResponseObject, error)
	// Revoke access or refresh token
	// (POST /auth/oauth2/revoke)
	Oauth2Revoke(ctx context.Context, request Oauth2RevokeRequestObject) (Oauth2RevokeResponseObject, error)
	// Exchange authorization code or refresh token for tokens
	// (POST /auth/oauth2/token)
	Oauth2Token(ctx context.Context, request Oauth2TokenRequestObject) (Oauth2TokenResponseObject, error)
	// Get current user information
	// (GET /auth/userinfo)
	GetUserInfo(ctx context.Context, request GetUserInfoRequestObject) (GetUserInfoResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostClaimAgent operation middleware
func (sh *strictHandler) PostClaimAgent(w http.ResponseWriter, r *http.Request) {
	var request PostClaimAgentRequestObject

	var body PostClaimAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostClaimAgent(ctx, request.(PostClaimAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostClaimAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostClaimAgentResponseObject); ok {
		if err := validResponse.VisitPostClaimAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterAgentSelf operation middleware
func (sh *strictHandler) RegisterAgentSelf(w http.ResponseWriter, r *http.Request) {
	var request RegisterAgentSelfRequestObject

	var body RegisterAgentSelfJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterAgentSelf(ctx, request.(RegisterAgentSelfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterAgentSelf")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterAgentSelfResponseObject); ok {
		if err := validResponse.VisitRegisterAgentSelfResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgentClaimStatus operation middleware
func (sh *strictHandler) GetAgentClaimStatus(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	var request GetAgentClaimStatusRequestObject

	request.AgentId = agentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentClaimStatus(ctx, request.(GetAgentClaimStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentClaimStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentClaimStatusResponseObject); ok {
		if err := validResponse.VisitGetAgentClaimStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgentConfiguration operation middleware
func (sh *strictHandler) GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	var request GetAgentConfigurationRequestObject

	request.AgentId = agentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentConfiguration(ctx, request.(GetAgentConfigurationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentConfiguration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentConfigurationResponseObject); ok {
		if err := validResponse.VisitGetAgentConfigurationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Oauth2Authorize operation middleware
func (sh *strictHandler) Oauth2Authorize(w http.ResponseWriter, r *http.Request, params Oauth2AuthorizeParams) {
	var request Oauth2AuthorizeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Oauth2Authorize(ctx, request.(Oauth2AuthorizeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Oauth2Authorize")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(Oauth2AuthorizeResponseObject); ok {
		if err := validResponse.VisitOauth2AuthorizeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Oauth2Callback operation middleware
func (sh *strictHandler) Oauth2Callback(w http.ResponseWriter, r *http.Request, params Oauth2CallbackParams) {
	var request Oauth2CallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Oauth2Callback(ctx, request.(Oauth2CallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Oauth2Callback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(Oauth2CallbackResponseObject); ok {
		if err := validResponse.VisitOauth2CallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Oauth2Revoke operation middleware
func (sh *strictHandler) Oauth2Revoke(w http.ResponseWriter, r *http.Request) {
	var request Oauth2RevokeRequestObject

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body Oauth2RevokeFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Oauth2Revoke(ctx, request.(Oauth2RevokeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Oauth2Revoke")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(Oauth2RevokeResponseObject); ok {
		if err := validResponse.VisitOauth2RevokeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Oauth2Token operation middleware
func (sh *strictHandler) Oauth2Token(w http.ResponseWriter, r *http.Request) {
	var request Oauth2TokenRequestObject

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body Oauth2TokenFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Oauth2Token(ctx, request.(Oauth2TokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Oauth2Token")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(Oauth2TokenResponseObject); ok {
		if err := validResponse.VisitOauth2TokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserInfo operation middleware
func (sh *strictHandler) GetUserInfo(w http.ResponseWriter, r *http.Request, params GetUserInfoParams) {
	var request GetUserInfoRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserInfo(ctx, request.(GetUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserInfoResponseObject); ok {
		if err := validResponse.VisitGetUserInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
