// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AgentApiKeyScopes             = "AgentApiKey.Scopes"
	OAuth2AuthorizationCodeScopes = "OAuth2AuthorizationCode.Scopes"
)

// Defines values for HealthStatusComponentsStatus.
const (
	HealthStatusComponentsStatusDegraded  HealthStatusComponentsStatus = "degraded"
	HealthStatusComponentsStatusHealthy   HealthStatusComponentsStatus = "healthy"
	HealthStatusComponentsStatusUnhealthy HealthStatusComponentsStatus = "unhealthy"
)

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusDegraded  HealthStatusStatus = "degraded"
	HealthStatusStatusHealthy   HealthStatusStatus = "healthy"
	HealthStatusStatusUnhealthy HealthStatusStatus = "unhealthy"
)

// AgentConfig defines model for AgentConfig.
type AgentConfig struct {
	// AgentId UUID version 7 as per RFC 4122
	AgentId UUIDv7 `json:"agent_id"`

	// AgentName Human-readable agent name
	AgentName string `json:"agent_name"`

	// Endpoints Endpoints to monitor
	Endpoints  []Endpoint       `json:"endpoints"`
	Monitoring MonitoringConfig `json:"monitoring"`
	Server     ServerConfig     `json:"server"`
	Storage    StorageConfig    `json:"storage"`

	// Tags Tags for this agent (used for mesh organization)
	Tags *[]string `json:"tags,omitempty"`

	// Version Configuration version (used for syncing with server)
	Version int32 `json:"version"`
}

// Endpoint defines model for Endpoint.
type Endpoint struct {
	// Address IP address, hostname, or URL
	Address string `json:"address"`
	Enabled bool   `json:"enabled"`

	// Id UUID version 7 as per RFC 4122
	Id   UUIDv7 `json:"id"`
	Port *int   `json:"port,omitempty"`

	// Tags Tags associated with the target
	Tags *[]string `json:"tags,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Details *[]struct {
		Field *string `json:"field,omitempty"`
		Issue *string `json:"issue,omitempty"`
	} `json:"details,omitempty"`

	// DocumentationUrl Link to relevant documentation
	DocumentationUrl *string             `json:"documentation_url,omitempty"`
	Error            string              `json:"error"`
	Message          string              `json:"message"`
	RequestId        *openapi_types.UUID `json:"request_id,omitempty"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Components *map[string]struct {
		Message        *string                      `json:"message,omitempty"`
		ResponseTimeMs *float32                     `json:"response_time_ms,omitempty"`
		Status         HealthStatusComponentsStatus `json:"status"`
	} `json:"components,omitempty"`
	Status        HealthStatusStatus `json:"status"`
	Timestamp     time.Time          `json:"timestamp"`
	UptimeSeconds *int               `json:"uptime_seconds,omitempty"`
	Version       *string            `json:"version,omitempty"`
}

// HealthStatusComponentsStatus defines model for HealthStatus.Components.Status.
type HealthStatusComponentsStatus string

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// MonitoringConfig defines model for MonitoringConfig.
type MonitoringConfig struct {
	// IntervalSecs Interval between checks in seconds
	IntervalSecs int64 `json:"interval_secs"`

	// MaxConcurrent Maximum number of concurrent checks
	MaxConcurrent int `json:"max_concurrent"`

	// PingCount Number of pings to send per check
	PingCount int32 `json:"ping_count"`

	// TimeoutSecs Timeout for each check in seconds
	TimeoutSecs int64 `json:"timeout_secs"`

	// TracerouteMaxHops Maximum TTL for traceroute
	TracerouteMaxHops int32 `json:"traceroute_max_hops"`

	// TracerouteOnFailure Enable traceroute on failed pings
	TracerouteOnFailure bool `json:"traceroute_on_failure"`
}

// ServerConfig defines model for ServerConfig.
type ServerConfig struct {
	// ApiKey API key for authentication
	ApiKey *string `json:"api_key"`

	// HeartbeatIntervalSecs Heartbeat interval in seconds
	HeartbeatIntervalSecs int64 `json:"heartbeat_interval_secs"`

	// ReportIntervalSecs Report interval in seconds
	ReportIntervalSecs int64 `json:"report_interval_secs"`

	// RetryAttempts Retry attempts on failure
	RetryAttempts int32 `json:"retry_attempts"`

	// TimeoutSecs Connection timeout in seconds
	TimeoutSecs int64 `json:"timeout_secs"`

	// Url Server URL
	Url *string `json:"url"`

	// VerifyTls Enable TLS verification
	VerifyTls bool `json:"verify_tls"`
}

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// CacheDir Directory for storing cached data
	CacheDir string `json:"cache_dir"`

	// MaxCacheAgeSecs Maximum age of cached results in seconds (e.g., 86400 = 24 hours)
	MaxCacheAgeSecs int64 `json:"max_cache_age_secs"`

	// MaxCachedResults Maximum number of results to cache
	MaxCachedResults int `json:"max_cached_results"`
}

// UUIDv7 UUID version 7 as per RFC 4122
type UUIDv7 = uuid.UUID

// AgentId UUID version 7 as per RFC 4122
type AgentId = UUIDv7

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// NotImplemented defines model for NotImplemented.
type NotImplemented = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get agent configuration
	// (GET /agent/{agentId}/configuration)
	GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId)
	// Health check endpoint
	// (GET /healthz)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Liveness check
	// (GET /healthz/live)
	LivenessCheck(w http.ResponseWriter, r *http.Request)
	// Readiness check
	// (GET /healthz/ready)
	ReadinessCheck(w http.ResponseWriter, r *http.Request)
	// Prometheus metrics endpoint
	// (GET /metrics)
	PrometheusMetrics(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get agent configuration
// (GET /agent/{agentId}/configuration)
func (_ Unimplemented) GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /healthz)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness check
// (GET /healthz/live)
func (_ Unimplemented) LivenessCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness check
// (GET /healthz/ready)
func (_ Unimplemented) ReadinessCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Prometheus metrics endpoint
// (GET /metrics)
func (_ Unimplemented) PrometheusMetrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAgentConfiguration operation middleware
func (siw *ServerInterfaceWrapper) GetAgentConfiguration(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "agentId" -------------
	var agentId AgentId

	err = runtime.BindStyledParameterWithOptions("simple", "agentId", chi.URLParam(r, "agentId"), &agentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, AgentApiKeyScopes, []string{})

	ctx = context.WithValue(ctx, OAuth2AuthorizationCodeScopes, []string{"agent:read"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentConfiguration(w, r, agentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LivenessCheck operation middleware
func (siw *ServerInterfaceWrapper) LivenessCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LivenessCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadinessCheck operation middleware
func (siw *ServerInterfaceWrapper) ReadinessCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadinessCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PrometheusMetrics operation middleware
func (siw *ServerInterfaceWrapper) PrometheusMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PrometheusMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/agent/{agentId}/configuration", wrapper.GetAgentConfiguration)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz/live", wrapper.LivenessCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz/ready", wrapper.ReadinessCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/metrics", wrapper.PrometheusMetrics)
	})

	return r
}

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type NotImplementedJSONResponse Error

type UnauthorizedJSONResponse Error

type GetAgentConfigurationRequestObject struct {
	AgentId AgentId `json:"agentId"`
}

type GetAgentConfigurationResponseObject interface {
	VisitGetAgentConfigurationResponse(w http.ResponseWriter) error
}

type GetAgentConfiguration200JSONResponse AgentConfig

func (response GetAgentConfiguration200JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAgentConfiguration401JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAgentConfiguration404JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration501JSONResponse struct{ NotImplementedJSONResponse }

func (response GetAgentConfiguration501JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentConfiguration503JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetAgentConfiguration503JSONResponse) VisitGetAgentConfigurationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheckRequestObject struct {
}

type HealthCheckResponseObject interface {
	VisitHealthCheckResponse(w http.ResponseWriter) error
}

type HealthCheck200JSONResponse HealthStatus

func (response HealthCheck200JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HealthCheck503JSONResponse HealthStatus

func (response HealthCheck503JSONResponse) VisitHealthCheckResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type LivenessCheckRequestObject struct {
}

type LivenessCheckResponseObject interface {
	VisitLivenessCheckResponse(w http.ResponseWriter) error
}

type LivenessCheck200Response struct {
}

func (response LivenessCheck200Response) VisitLivenessCheckResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ReadinessCheckRequestObject struct {
}

type ReadinessCheckResponseObject interface {
	VisitReadinessCheckResponse(w http.ResponseWriter) error
}

type ReadinessCheck200Response struct {
}

func (response ReadinessCheck200Response) VisitReadinessCheckResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ReadinessCheck503Response struct {
}

func (response ReadinessCheck503Response) VisitReadinessCheckResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type PrometheusMetricsRequestObject struct {
}

type PrometheusMetricsResponseObject interface {
	VisitPrometheusMetricsResponse(w http.ResponseWriter) error
}

type PrometheusMetrics200TextResponse string

func (response PrometheusMetrics200TextResponse) VisitPrometheusMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get agent configuration
	// (GET /agent/{agentId}/configuration)
	GetAgentConfiguration(ctx context.Context, request GetAgentConfigurationRequestObject) (GetAgentConfigurationResponseObject, error)
	// Health check endpoint
	// (GET /healthz)
	HealthCheck(ctx context.Context, request HealthCheckRequestObject) (HealthCheckResponseObject, error)
	// Liveness check
	// (GET /healthz/live)
	LivenessCheck(ctx context.Context, request LivenessCheckRequestObject) (LivenessCheckResponseObject, error)
	// Readiness check
	// (GET /healthz/ready)
	ReadinessCheck(ctx context.Context, request ReadinessCheckRequestObject) (ReadinessCheckResponseObject, error)
	// Prometheus metrics endpoint
	// (GET /metrics)
	PrometheusMetrics(ctx context.Context, request PrometheusMetricsRequestObject) (PrometheusMetricsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAgentConfiguration operation middleware
func (sh *strictHandler) GetAgentConfiguration(w http.ResponseWriter, r *http.Request, agentId AgentId) {
	var request GetAgentConfigurationRequestObject

	request.AgentId = agentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentConfiguration(ctx, request.(GetAgentConfigurationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentConfiguration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentConfigurationResponseObject); ok {
		if err := validResponse.VisitGetAgentConfigurationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HealthCheck operation middleware
func (sh *strictHandler) HealthCheck(w http.ResponseWriter, r *http.Request) {
	var request HealthCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HealthCheck(ctx, request.(HealthCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HealthCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthCheckResponseObject); ok {
		if err := validResponse.VisitHealthCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LivenessCheck operation middleware
func (sh *strictHandler) LivenessCheck(w http.ResponseWriter, r *http.Request) {
	var request LivenessCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LivenessCheck(ctx, request.(LivenessCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LivenessCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LivenessCheckResponseObject); ok {
		if err := validResponse.VisitLivenessCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReadinessCheck operation middleware
func (sh *strictHandler) ReadinessCheck(w http.ResponseWriter, r *http.Request) {
	var request ReadinessCheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReadinessCheck(ctx, request.(ReadinessCheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReadinessCheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadinessCheckResponseObject); ok {
		if err := validResponse.VisitReadinessCheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PrometheusMetrics operation middleware
func (sh *strictHandler) PrometheusMetrics(w http.ResponseWriter, r *http.Request) {
	var request PrometheusMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PrometheusMetrics(ctx, request.(PrometheusMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PrometheusMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PrometheusMetricsResponseObject); ok {
		if err := validResponse.VisitPrometheusMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
