server:
    host: 0.0.0.0
    port: 8080
    # read_timeout: 15s
    # write_timeout: 15s
    # idle_timeout: 2m0s
    # shutdown_timeout: 30s
    environment: development
database_type: sqlite
sqlite_config:
    config:
        type: sqlite
        # maxopenconns: 25
        # maxidleconns: 5
        # connmaxlifetime: 15m0s
        # connmaxidletime: 5m0s
    filepath: ./data/smotra.db
logging:
    level: debug
    format: text
auth:
    frontend_callback_url: http://localhost:3000/auth/callback
    server_callback_url: http://localhost:8080/v1/auth/oauth2/callback
    providers:
        auth0:
            type: oidc
            client_id: ZPsNwOIn7DiPHEjhbfy8zkXDj1hl0BD6
            issuer_url: https://dev-7ffv2mlfow4w0de7.us.auth0.com/
        # Example: configure GitHub for local dev
        # github:
        #     type: static
        #     client_id: your-github-client-id
        # Example: configure Google OIDC
        # google:
        #     type: oidc
        #     issuer_url: https://accounts.google.com
        #     client_id: your-google-client-id
agent:
    claim_token_expiration_hours: 24
    server_url: https://smotra.net
    claim_poll_initial_interval_secs: 5
    claim_poll_increment_secs: 5
    claim_poll_max_interval_secs: 30
cors:
    origin: http://localhost:3000
