package main

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	"github.com/go-chi/chi/v5"
	"github.com/smotra-monitoring/server/internal/config"
	"github.com/smotra-monitoring/server/internal/database"
	"github.com/smotra-monitoring/server/internal/handlers/health"
	"github.com/smotra-monitoring/server/internal/logger"
	"github.com/smotra-monitoring/server/internal/middleware"
	"github.com/smotra-monitoring/server/pkg/api"
)

const version = "0.0.1"

func main() {
	// Parse command line flags
	configFile := flag.String("c", "config.yaml", "Path to configuration file")
	flag.Parse()

	if *configFile == "" || configFile == nil {
		fmt.Fprintf(os.Stderr, "Configuration file path cannot be empty\n")
		os.Exit(1)
	}

	cfg, err := config.LoadAndValidate(*configFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to load configuration: %v\n", err)
		os.Exit(1)
	}

	// Initialize logger
	log := logger.New(logger.Config{
		Level:  cfg.Logging.Level,
		Format: cfg.Logging.Format,
	})

	log.Info("starting smotra monitoring server",
		"version", version,
		"environment", cfg.Server.Environment,
	)

	// Initialize database
	var db database.Database
	switch cfg.DatabaseType {
	case "postgres":
		db = database.NewPostgresDB(*cfg.PostgresConfig)
	case "sqlite":
		db = database.NewSQLiteDB(*cfg.SQLiteConfig)
	default:
		err = fmt.Errorf("unsupported database type: %s", cfg.DatabaseType)
	}

	if err != nil {
		log.Error("failed to create database", "error", err)
		os.Exit(1)
	}

	db_ctx := context.Background()
	if err := db.Open(db_ctx); err != nil {
		log.Error("failed to open database", "error", err)
		os.Exit(1)
	}

	defer db.Close()

	log.Info("database connection established", "type", cfg.DatabaseType)

	// Create router
	r := chi.NewRouter()

	// Global middleware
	r.Use(middleware.Logger(log))
	r.Use(middleware.RequestID)
	r.Use(middleware.Recovery(log))
	r.Use(middleware.CORS)

	// Initialize handlers
	healthHandler := health.NewHandler(log, db, version)

	// Health check routes (no authentication required)
	r.Get("/healthz", healthHandler.HealthCheck)
	r.Get("/healthz/ready", healthHandler.ReadinessCheck)
	// r.Get("/healthz/live", func(w http.ResponseWriter, r *http.Request) {
	// 	// Adapter for OpenAPI handler signature
	// 	resp, err := healthHandler.LivenessCheck(r.Context(), /* construct api.LivenessCheckRequestObject if needed */)
	// 	if err != nil {
	// 		http.Error(w, err.Error(), http.StatusInternalServerError)
	// 		return
	// 	}
	// 	// Assuming resp has a WriteResponse method as generated by oapi-codegen
	// 	resp.WriteResponse(w)
	// })

	strictHandler := api.NewStrictHandler(healthHandler, nil)
	r.Mount("/healthz/live", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		strictHandler.LivenessCheck(w, r)
	}))

	// api.HandlerFromMux(livenessCheck, r)

	// API v1 routes
	r.Route("/api/v1", func(r chi.Router) {
		// Future API endpoints will be added here
		r.Get("/", func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.Write([]byte(`{"message":"Smotra Monitoring API v1","version":"` + version + `"}`))
		})
	})

	// Create HTTP server
	srv := &http.Server{
		Addr:         fmt.Sprintf("%s:%d", cfg.Server.Host, cfg.Server.Port),
		Handler:      r,
		ReadTimeout:  cfg.Server.ReadTimeout,
		WriteTimeout: cfg.Server.WriteTimeout,
		IdleTimeout:  cfg.Server.IdleTimeout,
	}

	// Server run context
	serverCtx, serverStopCtx := context.WithCancel(context.Background())

	// Listen for syscall signals for process to interrupt/quit
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGHUP, syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT)

	// Start server in a goroutine
	go func() {
		log.Info("server starting",
			"address", srv.Addr,
			"environment", cfg.Server.Environment,
		)

		// Mark server as ready
		healthHandler.SetReady(true)

		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Error("server error", "error", err)
			os.Exit(1)
		}
	}()

	// Wait for signal
	<-sig

	// Shutdown signal received
	log.Info("shutting down server gracefully")

	// Mark server as not ready
	healthHandler.SetReady(false)

	// Shutdown context with timeout
	shutdownCtx, shutdownCancel := context.WithTimeout(serverCtx, cfg.Server.ShutdownTimeout)
	defer shutdownCancel()

	// Attempt graceful shutdown
	go func() {
		if err := srv.Shutdown(shutdownCtx); err != nil {
			log.Error("server shutdown error", "error", err)
		}
		serverStopCtx()
	}()

	// Wait for shutdown to complete or timeout
	<-shutdownCtx.Done()
	if shutdownCtx.Err() == context.DeadlineExceeded {
		log.Warn("shutdown timeout exceeded, forcing shutdown")
	}

	log.Info("server stopped")
}
